//! Singularity Economy Model v2 — systems-dynamics core (Meadows formalization).
//!
//! 1:1 port of `../../model_v2.py`. The Python implementation is the
//! specification; `tests/parity.rs` enforces agreement against golden vectors
//! generated by it. Design rationale: `../../meadows_design.md`.
//!
//! Loops (each with an ablation gain in [`Loops`]):
//!   B1 supply response, B2 displacement backlash, B3 affordability,
//!   R1 saturating recursive AI, R2 robot bootstrap, R3 capex momentum,
//!   B4 credit discipline.

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Parameters
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Loops {
    pub b1_supply_response: f64,
    pub b2_backlash: f64,
    pub b3_affordability: f64,
    pub r1_recursive_ai: f64,
    pub r2_robot_bootstrap: f64,
    pub r3_capex_momentum: f64,
    pub b4_credit: f64,
}

impl Default for Loops {
    fn default() -> Self {
        Loops {
            b1_supply_response: 1.0,
            b2_backlash: 1.0,
            b3_affordability: 1.0,
            r1_recursive_ai: 1.0,
            r2_robot_bootstrap: 1.0,
            r3_capex_momentum: 1.0,
            b4_credit: 1.0,
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Params {
    // timeline
    pub start_year: i32,
    pub end_year: i32,
    pub singularity_year: i32,
    pub robotics_year: i32,
    // macro baseline
    pub world_gdp: f64,
    pub cognitive_wage_bill: f64,
    pub physical_wage_bill: f64,
    pub cognitive_workers_m: f64,
    pub physical_workers_m: f64,
    pub base_gdp_growth: f64,
    pub productivity_passthrough: f64,
    pub transition_drag: f64,
    // casualty pools
    pub it_services_pool: f64,
    pub bpo_pool: f64,
    pub seat_saas_pool: f64,
    pub prof_info_pool: f64,
    pub it_services_beta: f64,
    pub bpo_beta: f64,
    pub saas_beta: f64,
    pub prof_info_beta: f64,
    // compute / silicon
    pub ai_capex_2026: f64,
    pub compute_deprec: f64,
    pub silicon_share_of_capex: f64,
    pub chip_capacity_2026: f64,
    pub chip_base_growth: f64,
    pub chip_supply_gain: f64,
    pub chip_growth_ceiling: f64,
    pub chip_pipeline_stages: usize,
    pub hw_cost_decline: f64,
    // power
    pub ai_power_2026: f64,
    pub power_additions_2026: f64,
    pub power_base_growth: f64,
    pub power_supply_gain: f64,
    pub power_growth_ceiling: f64,
    pub power_pipeline_stages: usize,
    pub gw_per_compute_unit: f64,
    pub power_efficiency_gain: f64,
    pub power_equip_cost_per_gw: f64,
    pub electricity_price_normal: f64,
    // AI cognitive supply / demand
    pub ai_hew_2026_m: f64,
    pub algo_eff_growth_pre: f64,
    pub singularity_boost: f64,
    pub recursive_years: i32,
    pub algo_eff_growth_post: f64,
    pub algo_eff_cap: f64,
    pub adoption_halflife: f64,
    pub max_displacement_rate: f64,
    pub backlash_gain: f64,
    pub afford_gain: f64,
    pub cognitive_demand_elasticity: f64,
    pub ai_task_price_rel: f64,
    pub addressable_cognitive: f64,
    // robotics
    pub robot_prod_2028_m: f64,
    pub component_capacity_2028: f64,
    pub component_base_growth: f64,
    pub component_supply_gain: f64,
    pub component_growth_ceiling: f64,
    pub component_pipeline_stages: usize,
    pub bootstrap_gain: f64,
    pub robot_cost_2028_k: f64,
    pub robot_learning_rate: f64,
    pub robot_cost_floor_k: f64,
    pub robot_hew: f64,
    pub robot_attrition: f64,
    pub physical_addressable: f64,
    pub max_physical_displacement_rate: f64,
    // capital / margins / credit
    pub capex_gdp_cap: f64,
    pub internal_funding_share: f64,
    pub credit_gain: f64,
    pub debt_revenue_tolerance: f64,
    pub normal_margin: f64,
    pub rent_margin_slope: f64,
    pub margin_ceiling: f64,
    pub target_utilization: f64,
    pub ai_services_margin: f64,
    // capex behavior
    pub perception_smoothing: f64,
    pub momentum_gain: f64,
    pub demand_growth_base: f64,

    pub loops: Loops,
}

impl Default for Params {
    fn default() -> Self {
        Params {
            start_year: 2026,
            end_year: 2036,
            singularity_year: 2027,
            robotics_year: 2028,
            world_gdp: 115.0,
            cognitive_wage_bill: 28.0,
            physical_wage_bill: 34.0,
            cognitive_workers_m: 950.0,
            physical_workers_m: 2400.0,
            base_gdp_growth: 0.03,
            productivity_passthrough: 0.35,
            transition_drag: 0.5,
            it_services_pool: 1.55,
            bpo_pool: 0.36,
            seat_saas_pool: 0.35,
            prof_info_pool: 0.45,
            it_services_beta: 0.9,
            bpo_beta: 1.25,
            saas_beta: 0.75,
            prof_info_beta: 0.35,
            ai_capex_2026: 0.65,
            compute_deprec: 0.25,
            silicon_share_of_capex: 0.55,
            chip_capacity_2026: 0.36,
            chip_base_growth: 0.30,
            chip_supply_gain: 1.6,
            chip_growth_ceiling: 0.85,
            chip_pipeline_stages: 2,
            hw_cost_decline: 0.15,
            ai_power_2026: 55.0,
            power_additions_2026: 24.0,
            power_base_growth: 0.08,
            power_supply_gain: 0.55,
            power_growth_ceiling: 0.40,
            power_pipeline_stages: 3,
            gw_per_compute_unit: 55.0,
            power_efficiency_gain: 0.12,
            power_equip_cost_per_gw: 0.0035,
            electricity_price_normal: 0.055,
            ai_hew_2026_m: 12.0,
            algo_eff_growth_pre: 2.5,
            singularity_boost: 2.0,
            recursive_years: 3,
            algo_eff_growth_post: 1.5,
            algo_eff_cap: 3000.0,
            adoption_halflife: 1.6,
            max_displacement_rate: 0.22,
            backlash_gain: 2.0,
            afford_gain: 0.8,
            cognitive_demand_elasticity: 1.35,
            ai_task_price_rel: 0.04,
            addressable_cognitive: 0.85,
            robot_prod_2028_m: 0.12,
            component_capacity_2028: 0.14,
            component_base_growth: 0.45,
            component_supply_gain: 2.2,
            component_growth_ceiling: 1.4,
            component_pipeline_stages: 2,
            bootstrap_gain: 0.10,
            robot_cost_2028_k: 50.0,
            robot_learning_rate: 0.22,
            robot_cost_floor_k: 8.0,
            robot_hew: 1.4,
            robot_attrition: 0.08,
            physical_addressable: 0.65,
            max_physical_displacement_rate: 0.15,
            capex_gdp_cap: 0.055,
            internal_funding_share: 0.65,
            credit_gain: 1.2,
            debt_revenue_tolerance: 1.5,
            normal_margin: 0.22,
            rent_margin_slope: 0.35,
            margin_ceiling: 0.62,
            target_utilization: 0.85,
            ai_services_margin: 0.35,
            perception_smoothing: 0.5,
            momentum_gain: 0.5,
            demand_growth_base: 0.32,
            loops: Loops::default(),
        }
    }
}

// ---------------------------------------------------------------------------
// Pipeline: N-stage conserving material delay
// ---------------------------------------------------------------------------

#[derive(Clone, Debug)]
pub struct Pipeline {
    stages: Vec<f64>,
}

impl Pipeline {
    pub fn new(stages: usize, initial_flow: f64) -> Self {
        Pipeline { stages: vec![initial_flow; stages] }
    }

    /// Advance one year; returns delivered outflow.
    pub fn step(&mut self, inflow: f64) -> f64 {
        let mut carry = inflow;
        for slot in self.stages.iter_mut() {
            let out = *slot;
            *slot = carry;
            carry = out;
        }
        carry
    }

    pub fn in_transit(&self) -> f64 {
        self.stages.iter().sum()
    }

    pub fn first_stage(&self) -> f64 {
        self.stages.first().copied().unwrap_or(0.0)
    }
}

fn logistic(x: f64) -> f64 {
    1.0 / (1.0 + (-x).exp())
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Binding {
    Power,
    Chips,
    Capital,
    Demand,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Pools {
    pub ai_services: f64,
    pub silicon: f64,
    pub dc_infra: f64,
    pub power_equipment: f64,
    pub electricity: f64,
    pub robots: f64,
    pub robot_components: f64,
    pub robot_services: f64,
    pub it_services: f64,
    pub bpo: f64,
    pub seat_saas: f64,
    pub prof_info: f64,
    pub human_cognitive_wages: f64,
    pub human_physical_wages: f64,
    pub gdp_index: f64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct YearState {
    pub year: i32,
    pub binding: Binding,
    pub ai_capex: f64,
    pub compute_stock: f64,
    pub algo_eff: f64,
    pub ai_power_gw: f64,
    pub power_utilization: f64,
    pub chip_utilization: f64,
    pub silicon_margin: f64,
    pub power_margin: f64,
    pub component_margin: f64,
    pub electricity_price: f64,
    pub ai_hew_m: f64,
    pub cog_displacement: f64,
    pub cognitive_task_index: f64,
    pub adoption_friction: f64,
    pub robot_prod_m: f64,
    pub robot_fleet_m: f64,
    pub robot_cost_k: f64,
    pub component_capacity_m: f64,
    pub phys_displacement: f64,
    pub sector_debt: f64,
    pub credit_multiplier: f64,
    pub perceived_growth: f64,
    pub overshoot_ratio: f64,
    pub gdp: f64,
    pub pools: Pools,
}

// ---------------------------------------------------------------------------
// Simulation
// ---------------------------------------------------------------------------

fn power_orders(p: &Params, power_margin: f64, perceived_growth: f64,
                pipe: &Pipeline) -> f64 {
    let current_rate = if pipe.stages.is_empty() {
        p.power_additions_2026
    } else {
        pipe.first_stage()
    };
    let excess = (power_margin - p.normal_margin).max(0.0);
    let growth = (p.power_base_growth
        + p.loops.b1_supply_response * p.power_supply_gain * excess
        + 0.3 * (perceived_growth - 0.3).max(0.0))
        .min(p.power_growth_ceiling);
    current_rate * (1.0 + growth)
}

pub fn simulate(p: &Params) -> Vec<YearState> {
    let l = &p.loops;

    // stocks
    let mut compute_stock = 1.0_f64;
    let mut algo_eff = 1.0_f64;
    let mut ai_power = p.ai_power_2026;
    let mut chip_capacity = p.chip_capacity_2026;
    let mut component_capacity = 0.0_f64;
    let mut robot_fleet = 0.0_f64;
    let mut cum_robots = 0.02_f64;
    let mut robot_cost = p.robot_cost_2028_k;
    #[allow(unused_assignments)]
    let mut human_cog_m = p.cognitive_workers_m;
    let mut phys_workers_m = p.physical_workers_m;
    let mut gdp = p.world_gdp;
    let mut sector_debt = 0.0_f64;
    let mut perceived_growth = p.demand_growth_base;
    let mut last_capex = p.ai_capex_2026 * 0.8;
    let mut prev_disp = 0.0_f64;
    let mut prev_disp_macro = 0.0_f64;
    let mut gw_per_unit = p.gw_per_compute_unit;

    let mut power_pipe = Pipeline::new(p.power_pipeline_stages, p.power_additions_2026);
    let mut chip_pipe = Pipeline::new(p.chip_pipeline_stages,
                                      chip_capacity * p.chip_base_growth);
    let mut comp_pipe = Pipeline::new(p.component_pipeline_stages, 0.0);

    let mut silicon_margin = p.normal_margin + 0.10;
    let mut power_margin = p.normal_margin + 0.08;
    let mut component_margin = p.normal_margin;

    let mut out: Vec<YearState> = Vec::new();

    for year in p.start_year..=p.end_year {
        let t_sing = year - p.singularity_year;

        // ---- R1: recursive AI (saturating) ----
        if year > p.start_year {
            let g = if year <= p.singularity_year {
                p.algo_eff_growth_pre
            } else if t_sing <= p.recursive_years {
                let boost = 1.0 + (p.singularity_boost - 1.0) * l.r1_recursive_ai;
                p.algo_eff_growth_pre * boost
            } else {
                p.algo_eff_growth_post
            };
            let headroom = (1.0 - algo_eff / p.algo_eff_cap).max(0.0);
            algo_eff *= 1.0 + (g - 1.0) * headroom;
        }

        // ---- demand side: adoption with B2 + B3 ----
        let recent_disp_rate = if out.len() >= 2 {
            (out[out.len() - 1].cog_displacement
                - out[out.len() - 2].cog_displacement).max(0.0)
        } else if !out.is_empty() {
            out[out.len() - 1].cog_displacement
        } else {
            0.0
        };
        let friction = 1.0 + l.b2_backlash * p.backlash_gain * recent_disp_rate;

        let btl_price = if let Some(prev) = out.last() {
            let b = prev.power_utilization.max(prev.chip_utilization);
            (b - p.target_utilization).max(0.0) / (1.0 - p.target_utilization)
        } else {
            0.4
        };
        let afford = 1.0 + l.b3_affordability * p.afford_gain * btl_price;

        let adopt = if t_sing < 0 {
            (0.08 * 1.6_f64.powi(year - p.start_year)).min(0.28)
        } else {
            let k = 3.0_f64.ln() / (p.adoption_halflife * friction);
            logistic(k * (t_sing as f64 - p.adoption_halflife * friction)).max(0.10)
        };

        let ai_hew_raw = p.ai_hew_2026_m * compute_stock * algo_eff;
        let price_ratio = if t_sing >= 0 { p.ai_task_price_rel * afford } else { 0.25 };
        let task_expansion = price_ratio
            .powf(-(p.cognitive_demand_elasticity - 1.0) * 0.35)
            .min(6.0);
        let cognitive_task_index = 1.0 + (task_expansion - 1.0) * adopt;
        let addressable = p.cognitive_workers_m * p.addressable_cognitive;
        let demand_hew = addressable * adopt * cognitive_task_index;
        let ai_hew = ai_hew_raw.min(demand_hew);

        let disp_target = (ai_hew / cognitive_task_index.max(1e-9)).min(addressable)
            / p.cognitive_workers_m;
        let mut disp = (disp_target * (adopt * 1.4).min(1.0))
            .min(prev_disp + p.max_displacement_rate / friction);
        disp = disp.max(prev_disp);
        prev_disp = disp;
        human_cog_m = p.cognitive_workers_m * (1.0 - disp);

        // ---- R3: capex desire from perceived demand ----
        let mut demand_signal_growth = p.demand_growth_base;
        if t_sing >= 0 {
            let prev_adopt_level = out.last().map_or(0.0, |s| s.cog_displacement);
            demand_signal_growth +=
                1.6 * (adopt - prev_adopt_level).max(0.0) + 0.5 * adopt;
        }
        perceived_growth += p.perception_smoothing
            * (demand_signal_growth - perceived_growth);
        let herd = l.r3_capex_momentum * p.momentum_gain * perceived_growth.max(0.0);
        let desired_capex = last_capex * (1.0 + perceived_growth + herd);

        // ---- B4: credit ----
        let ai_revenue_proxy = (out.last().map_or(0.02, |s| s.pools.ai_services)
            + 0.25 * last_capex)
            .max(0.05);
        let leverage = sector_debt / ai_revenue_proxy.max(1e-9);
        let credit_mult = 1.0
            / (1.0 + l.b4_credit * p.credit_gain
                * (leverage - p.debt_revenue_tolerance).max(0.0));

        // ---- constraints ----
        let hw_cost_index = (1.0 - p.hw_cost_decline).powi(year - p.start_year);
        let cost_per_unit = (p.ai_capex_2026 / 0.80) * hw_cost_index;

        let chips_cap = chip_capacity / p.silicon_share_of_capex;
        gw_per_unit *= 1.0 - p.power_efficiency_gain;
        let orders = power_orders(p, power_margin, perceived_growth, &power_pipe);
        let power_additions = power_pipe.step(orders);
        let power_headroom =
            (ai_power + power_additions - compute_stock * gw_per_unit).max(0.0);
        let power_cap = (power_headroom / gw_per_unit) * cost_per_unit;
        let capital_cap = gdp * p.capex_gdp_cap * credit_mult;

        let caps = [
            (Binding::Chips, chips_cap),
            (Binding::Power, power_cap),
            (Binding::Capital, capital_cap),
            (Binding::Demand, desired_capex),
        ];
        // min by value; tie-break order matches Python dict iteration
        // (chips, power, capital, demand) with strict '<'
        let (mut binding, mut ai_capex) = (Binding::Chips, chips_cap);
        for &(b, v) in &caps[1..] {
            if v < ai_capex {
                binding = b;
                ai_capex = v;
            }
        }
        let overshoot_ratio = desired_capex / chips_cap.min(power_cap).max(1e-9);

        sector_debt += (ai_capex * (1.0 - p.internal_funding_share)).max(0.0);
        sector_debt *= 0.90;

        let units_added = ai_capex / cost_per_unit;
        compute_stock = compute_stock * (1.0 - p.compute_deprec) + units_added;
        ai_power = (ai_power + power_additions).max(compute_stock * gw_per_unit);
        let used_power = compute_stock * gw_per_unit;

        // ---- utilizations, prices, margins ----
        let chip_utilization = (desired_capex * p.silicon_share_of_capex
            / chip_capacity.max(1e-9))
            .min(1.35);
        let power_demand_gw = (desired_capex / cost_per_unit) * gw_per_unit
            + compute_stock * gw_per_unit * p.compute_deprec;
        let power_utilization = ((compute_stock * gw_per_unit + power_demand_gw * 0.5)
            / (ai_power + power_additions).max(1e-9))
            .min(1.35);

        let margin_from = |u: f64, gain_class: f64| -> f64 {
            let excess = (u - p.target_utilization).max(0.0)
                / (1.0 - p.target_utilization);
            (p.normal_margin + p.rent_margin_slope * excess.min(2.0) * gain_class)
                .min(p.margin_ceiling)
        };

        silicon_margin = margin_from(chip_utilization, 0.9);
        power_margin = margin_from(power_utilization, 1.0);
        let electricity_price = p.electricity_price_normal
            * (1.0 + 1.2 * (((power_utilization - p.target_utilization).max(0.0))
                / (1.0 - p.target_utilization))
                .min(2.0));

        // ---- B1: chip capacity supply response ----
        let excess_margin = (silicon_margin - p.normal_margin).max(0.0);
        let chip_growth = (p.chip_base_growth
            + l.b1_supply_response * p.chip_supply_gain * excess_margin)
            .min(p.chip_growth_ceiling);
        let delivered = chip_pipe.step(chip_capacity * chip_growth);
        chip_capacity += delivered;

        // ---- robotics ----
        let mut robot_prod = 0.0;
        if year >= p.robotics_year {
            if component_capacity == 0.0 {
                component_capacity = p.component_capacity_2028;
            }
            let comp_excess = (component_margin - p.normal_margin).max(0.0);
            let bootstrap = l.r2_robot_bootstrap * p.bootstrap_gain
                * (robot_fleet * 0.3).min(10.0);
            let comp_ceiling = p.component_growth_ceiling + bootstrap;
            let comp_growth = (p.component_base_growth
                + l.b1_supply_response * p.component_supply_gain * comp_excess
                + bootstrap * 0.2)
                .min(comp_ceiling);
            component_capacity += comp_pipe.step(component_capacity * comp_growth);

            let avg_phys_wage_k =
                p.physical_wage_bill / p.physical_workers_m * 1e3;
            let payback_years =
                robot_cost / (avg_phys_wage_k * p.robot_hew).max(1e-9);
            let econ_pull = (2.0 / payback_years.max(0.25)).min(3.0).max(0.0);
            let t_rob = (year - p.robotics_year) as f64;
            let deploy_ramp = logistic(0.9 * (t_rob - 4.0));
            let fleet_target = p.physical_workers_m * p.physical_addressable
                * deploy_ramp * (econ_pull / 2.0).min(1.0);
            let robot_demand = (fleet_target
                - robot_fleet * (1.0 - p.robot_attrition))
                .max(p.robot_prod_2028_m * 0.5);
            robot_prod = robot_demand.min(component_capacity);
            let comp_utilization = robot_demand / component_capacity.max(1e-9);
            component_margin = margin_from(comp_utilization.min(1.35), 0.8);

            cum_robots += robot_prod;
            let doublings = (cum_robots / 0.06).max(1.0).log2();
            robot_cost = (p.robot_cost_2028_k
                * (1.0 - p.robot_learning_rate).powf(doublings))
                .max(p.robot_cost_floor_k);
            robot_fleet = robot_fleet * (1.0 - p.robot_attrition) + robot_prod;
        }

        let phys_hew = robot_fleet * p.robot_hew;
        let pd_target =
            (phys_hew / p.physical_workers_m).min(p.physical_addressable);
        let prev_pd = 1.0 - phys_workers_m / p.physical_workers_m;
        let pd = pd_target
            .min(prev_pd + p.max_physical_displacement_rate)
            .max(prev_pd);
        phys_workers_m = p.physical_workers_m * (1.0 - pd);

        // ---- pools & profits ----
        let avg_cog_wage = p.cognitive_wage_bill / p.cognitive_workers_m;
        let avg_phys_wage = p.physical_wage_bill / p.physical_workers_m;
        let displaced_value = disp * p.cognitive_workers_m * avg_cog_wage;
        let ai_services = displaced_value * 0.45
            + (cognitive_task_index - 1.0) * p.cognitive_wage_bill * 0.06;

        let years_in = (year - p.start_year) as i32;
        let casualty = |pool0: f64, beta: f64, drift: f64| -> f64 {
            let organic = pool0 * (1.0 + drift).powi(years_in);
            organic * (1.0 - beta * disp).max(0.05)
        };

        let pools = Pools {
            ai_services,
            silicon: ai_capex * p.silicon_share_of_capex,
            dc_infra: ai_capex * (1.0 - p.silicon_share_of_capex),
            power_equipment: p.power_equip_cost_per_gw * power_additions,
            electricity: ai_power * 8760.0 * electricity_price / 1e6,
            robots: robot_prod * robot_cost / 1e3,
            robot_components: robot_prod * robot_cost / 1e3 * 0.55,
            robot_services: pd * p.physical_workers_m * avg_phys_wage * 0.35,
            it_services: casualty(p.it_services_pool, p.it_services_beta, 0.04),
            bpo: casualty(p.bpo_pool, p.bpo_beta, 0.03),
            seat_saas: casualty(p.seat_saas_pool, p.saas_beta, 0.08),
            prof_info: casualty(p.prof_info_pool, p.prof_info_beta, 0.05),
            human_cognitive_wages: human_cog_m * avg_cog_wage,
            human_physical_wages: phys_workers_m * avg_phys_wage,
            gdp_index: gdp,
        };

        // ---- macro ----
        let new_disp = (disp - prev_disp_macro).max(0.0);
        prev_disp_macro = disp;
        let ai_share = (ai_services + pools.robot_services) / gdp;
        gdp *= 1.0
            + (p.base_gdp_growth + p.productivity_passthrough * ai_share * 0.5
                - p.transition_drag * new_disp * (p.cognitive_wage_bill / gdp));

        last_capex = ai_capex.max(1e-6);

        out.push(YearState {
            year,
            binding,
            ai_capex,
            compute_stock,
            algo_eff,
            ai_power_gw: used_power,
            power_utilization,
            chip_utilization,
            silicon_margin,
            power_margin,
            component_margin,
            electricity_price,
            ai_hew_m: ai_hew,
            cog_displacement: disp,
            cognitive_task_index,
            adoption_friction: friction,
            robot_prod_m: robot_prod,
            robot_fleet_m: robot_fleet,
            robot_cost_k: robot_cost,
            component_capacity_m: component_capacity,
            phys_displacement: pd,
            sector_debt,
            credit_multiplier: credit_mult,
            perceived_growth,
            overshoot_ratio,
            gdp,
            pools,
        });
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pipeline_conserves() {
        let mut pipe = Pipeline::new(2, 0.0);
        let mut total_in = 0.0;
        let mut total_out = 0.0;
        for i in 0..10 {
            let inflow = i as f64;
            total_in += inflow;
            total_out += pipe.step(inflow);
        }
        assert!((total_in - total_out - pipe.in_transit()).abs() < 1e-9);
    }

    #[test]
    fn baseline_runs_and_power_binds() {
        let states = simulate(&Params::default());
        assert_eq!(states.len(), 11);
        let power_years = states.iter()
            .filter(|s| s.binding == Binding::Power).count();
        assert!(power_years >= 6, "power bound {} years", power_years);
    }
}
