//! Singularity Economy Model v2 — systems-dynamics core (Meadows formalization).
//!
//! 1:1 port of `../../model_v2.py`. The Python implementation is the
//! specification; `tests/parity.rs` enforces agreement against golden vectors
//! generated by it. Design rationale: `../../meadows_design.md`.
//!
//! Loops (each with an ablation gain in [`Loops`]):
//!   B1 supply response, B2 displacement backlash, B3 affordability,
//!   R1 saturating recursive AI, R2 robot bootstrap, R3 capex momentum,
//!   B4 credit discipline.

#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

pub mod bio;
pub mod companies;
pub mod demography;
pub mod geopolitics;
pub mod energy;
pub mod food;
pub mod macrofin;
pub mod materials;
pub mod regions;
pub mod scenarios;
pub mod society;
pub mod space;
pub mod valuation;

pub use bio::{BioOutputs, BioParams, BioState};
pub use demography::{DemographyOutputs, DemographyParams, DemographyState};
pub use geopolitics::{GeoRng, GeoShock, ShockKind};
pub use macrofin::{MacroParams, MacroState};
pub use society::{SocietyParams, SocietyState};
pub use space::{SpaceParams, SpaceState};

// ---------------------------------------------------------------------------
// Parameters
// ---------------------------------------------------------------------------

#[derive(Clone, Debug)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct Loops {
    pub b1_supply_response: f64,
    pub b2_backlash: f64,
    pub b3_affordability: f64,
    pub r1_recursive_ai: f64,
    pub r2_robot_bootstrap: f64,
    pub r3_capex_momentum: f64,
    pub b4_credit: f64,
    /// R4: post-singularity physical acceleration — ASI compresses
    /// engineering/commissioning delays, raises scaling ceilings, and
    /// dissolves robot-integration friction. Physics (materials, curing,
    /// forging) still binds; cognitive work hidden inside construction
    /// timelines does not.
    pub r4_physical_acceleration: f64,
    /// Society layer master switch: endogenous political economy
    /// (sentiment, transfers, regulation, labor power, trust). With 0.0
    /// the legacy constant-gain B2 behavior is exactly recovered.
    pub society_layer: f64,
    /// Demography layer switch: dynamic pools, hiring-freeze signal
    /// filter, youth blockage, care economy, migration/solidarity/tension
    /// politics. With 0.0 the static-pool legacy is exactly recovered.
    pub d_demography: f64,
    /// R5: Wright-law launch learning -> orbital-compute gate. With 0.0
    /// (and orbital_effectiveness 0) the terrestrial-only legacy is
    /// exactly recovered.
    pub r5_launch_learning: f64,
    /// B11: endogenous long rate / bond-market pricing of the transfer
    /// ramp. With 0.0 rates stay exogenous (legacy flat 12% DCF world).
    pub b11_endogenous_rates: f64,
}

impl Default for Loops {
    fn default() -> Self {
        Loops {
            b1_supply_response: 1.0,
            b2_backlash: 1.0,
            b3_affordability: 1.0,
            r1_recursive_ai: 1.0,
            r2_robot_bootstrap: 1.0,
            r3_capex_momentum: 1.0,
            b4_credit: 1.0,
            r4_physical_acceleration: 1.0,
            society_layer: 1.0,
            d_demography: 1.0,
            r5_launch_learning: 1.0,
            b11_endogenous_rates: 1.0,
        }
    }
}

#[derive(Clone, Debug)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct Params {
    // timeline
    pub start_year: i32,
    pub end_year: i32,
    pub singularity_year: i32,
    pub robotics_year: i32,
    // macro baseline
    pub world_gdp: f64,
    pub cognitive_wage_bill: f64,
    pub physical_wage_bill: f64,
    /// Wage-COMPRESSION gains (new-dynamic quick-win, default 0.0 = off, baseline
    /// preserved). Today the human wage pools fall only via HEADCOUNT
    /// (displacement); the average wage is frozen. But a growing reserve of
    /// displaced/underemployed labor also compresses the PRICE of the remaining
    /// jobs (a monopsony/oversupply channel), so the wage BILL falls faster than
    /// employment. When >0, the effective average wage tracks a target
    /// `1 - gain*displacement` (floored), reviving the wage-linked short sleeve
    /// (RHI/ADP/PAYX/MAN) that a headcount-only pool leaves under-punished.
    pub wage_compression_cog_gain: f64,
    pub wage_compression_phys_gain: f64,
    pub cognitive_workers_m: f64,
    pub physical_workers_m: f64,
    pub base_gdp_growth: f64,
    pub productivity_passthrough: f64,
    pub transition_drag: f64,
    // casualty pools
    pub it_services_pool: f64,
    pub bpo_pool: f64,
    pub seat_saas_pool: f64,
    pub prof_info_pool: f64,
    pub it_services_beta: f64,
    pub bpo_beta: f64,
    pub saas_beta: f64,
    pub prof_info_beta: f64,
    // compute / silicon
    pub ai_capex_2026: f64,
    pub compute_deprec: f64,
    pub silicon_share_of_capex: f64,
    pub chip_capacity_2026: f64,
    pub chip_base_growth: f64,
    pub chip_supply_gain: f64,
    pub chip_growth_ceiling: f64,
    pub chip_pipeline_stages: usize,
    pub hw_cost_decline: f64,
    // power
    pub ai_power_2026: f64,
    pub power_additions_2026: f64,
    /// Transmission/HVDC delivery-lag coupling (new-dynamic; 0 = off, baseline
    /// preserved). Today a generated GW is instantly a usable GW. In reality
    /// large power transformers, HVDC converters and substations are a SEPARATE
    /// lead-time bottleneck (GO-steel, ~2-4yr transformer lead times, Hitachi/
    /// Siemens/GEV backlogs), so deliverable power lags generation. When >0, the
    /// energized additions are capped by a transmission-throughput stock that ramps
    /// at `transmission_buildout_gwpy`; the gain in [0,1] scales how hard the cap
    /// binds. Tighter deliverable power = longer power rents (bullish GEV/POWL/
    /// VST/CEG — the bottleneck IS the grid-equipment makers' product).
    pub transmission_gain: f64,
    /// Transmission-capacity growth RATE (transformer/HVDC throughput). Kept below
    /// peak AI-power demand growth so it lags and binds in the boom.
    pub transmission_growth: f64,
    pub power_base_growth: f64,
    pub power_supply_gain: f64,
    pub power_growth_ceiling: f64,
    pub power_pipeline_stages: usize,
    pub gw_per_compute_unit: f64,
    pub power_efficiency_gain: f64,
    pub power_equip_cost_per_gw: f64,
    pub electricity_price_normal: f64,
    // AI cognitive supply / demand
    pub ai_hew_2026_m: f64,
    pub algo_eff_growth_pre: f64,
    pub singularity_boost: f64,
    pub recursive_years: i32,
    pub algo_eff_growth_post: f64,
    pub algo_eff_cap: f64,
    pub adoption_halflife: f64,
    pub max_displacement_rate: f64,
    /// Marginal returns to intelligence: economic labor supplied is
    /// (compute x algo_eff)^rho. rho=1 is the legacy linear assumption;
    /// rho<1 encodes task-coverage concavity — each capability doubling
    /// unlocks a SHRINKING marginal slice of economic tasks (the long
    /// tail of tasks is harder, less standardized, more embodied), plus
    /// Chinchilla-style log returns of capability to raw compute.
    /// Normalized at the 2026 anchor (compute x algo = 1), so t0
    /// calibration is invariant to rho.
    pub intelligence_returns_rho: f64,
    /// Jevons elasticity of compute DEMAND w.r.t. efficiency. 1.0 = the
    /// legacy assumption (demand rises exactly to fill efficiency gains,
    /// power neutral). <1 = efficiency jumps cut net power demand (the
    /// power-sleeve bear case); commodity tier ~1.25, frontier ~0.5.
    pub jevons_elasticity: f64,
    /// MC-drawn efficiency discontinuity: year of a >=10x algorithmic
    /// efficiency jump (0 = none). DeepSeek-R1-class (priced Jan 2025).
    pub efficiency_jump_year: i32,
    /// Size of that jump (multiplier on efficiency, e.g. 10.0).
    pub efficiency_jump_size: f64,
    pub backlash_gain: f64,
    pub afford_gain: f64,
    /// Society-layer parameters (sentiment, transfers, regulation, trust).
    pub society: society::SocietyParams,
    /// Demography-layer parameters (pools, youth, care, migration, tension).
    pub demography: demography::DemographyParams,
    /// Space-layer parameters (launch growth, orbital compute).
    pub space: space::SpaceParams,
    /// Macro-finance parameters (endogenous rates, sovereign snowball).
    pub macrofin: macrofin::MacroParams,
    /// Bio/cyber-layer parameters (drug pool, hazards, shadow optionality).
    pub bio: bio::BioParams,
    /// Critical-inputs supply chain (Liebig minimum over reducers, magnets,
    /// sensors, chips, copper — with China concentration + ASI substitution).
    pub materials: materials::MaterialsParams,
    /// Energy generation mix (solar+battery Wright exponentials vs gas+nuclear
    /// firm power) — the supply side of the power constraint.
    pub energy: energy::EnergyParams,
    /// Food production + food-price → political-unrest coupling (gas→fertilizer
    /// →food→tension chain).
    pub food: food::FoodParams,
    /// Regional political economy (US / China / EU divergence).
    pub regions: regions::RegionParams,
    /// Food-unrest → tension coupling gain (0 = satellite only; feeds the
    /// demography/society tension channel with a one-year lag).
    pub food_tension_gain: f64,
    /// Energy-layer → core electricity-price coupling gain (C3). 0 = the energy
    /// mix stays a pure satellite (baseline unchanged). >0 blends the energy
    /// layer's blended generation cost_index (solar+battery Wright's law drives
    /// it below 1.0) into the AI sector's effective electricity price, with a
    /// one-year lag — so cheap clean power actually relieves the core power/cost
    /// constraint instead of the price reflecting only datacenter utilization.
    pub energy_price_gain: f64,
    /// AI-capex bubble/bust reflexivity gain (new-dynamic spine; 0 = off, baseline
    /// preserved). Turns the model's smooth capacity glut into a reflexive
    /// boom-bust: buoyant `equity_sentiment` amplifies desired capex and eases
    /// credit (the R-loop valuations→capex→growth→valuations), then a capacity
    /// glut past ~1.3 cracks sentiment ASYMMETRICALLY (Minsky: booms build slowly,
    /// busts crash fast), cutting capex and tightening credit into the downturn.
    /// This is the Minsky/Soros loop the core otherwise lacks; it fattens the left
    /// tail on every silicon/power name.
    pub equity_sentiment_gain: f64,
    /// Compute-governance / licensing regime (new-dynamic B12 balancing loop; 0 =
    /// off, baseline preserved). The society layer throttles DIFFUSION (adoption);
    /// this throttles the R1 training flywheel at its SOURCE — a compute-cap /
    /// licensing regime that tightens as frontier capability (ASI) rises, so fewer
    /// compute units are added per dollar of capex. Caps the silicon/HBM
    /// scarcity-rent tail (NVDA/TSM/MU downside) and raises licensed-incumbent value.
    pub compute_governance_gain: f64,
    /// Equity wealth-effect on consumption (new-dynamic quick-win; 0 = off). Chains
    /// off the reflexivity spine: the YoY change in `equity_sentiment` (a valuation
    /// proxy for the AI-equity complex) transmits to real GDP via a marginal
    /// propensity to consume (~4c/$) scaled by the AI complex's share of wealth. It
    /// only bites when the spine is also on (a frozen sentiment has zero change), so
    /// it deepens the bust and froths the boom — making the broad GdpIndex pool
    /// genuinely cyclical rather than a smooth trend.
    pub wealth_effect_gain: f64,
    /// MC-drawn bio/cyber dread shocks (empty = baseline unchanged).
    pub dread_shocks: Vec<bio::shocks::DreadShock>,
    /// Open-weight model share (erodes bio safeguard efficacy).
    pub open_weight_share: f64,
    /// MC-drawn shock: calendar year an AI incident lands (0 = none).
    pub incident_year: i32,
    /// Whether that incident is dread-class (TMI pattern) vs ordinary-major.
    pub incident_dread: bool,
    /// MC-drawn geopolitical shock path (empty = deterministic baseline,
    /// exactly unchanged — the tail-module regression guard).
    pub geo_shocks: Vec<geopolitics::GeoShock>,
    pub cognitive_demand_elasticity: f64,
    pub ai_task_price_rel: f64,
    pub addressable_cognitive: f64,
    // robotics
    pub robot_prod_2028_m: f64,
    pub component_capacity_2028: f64,
    pub component_base_growth: f64,
    pub component_supply_gain: f64,
    pub component_growth_ceiling: f64,
    pub component_pipeline_stages: usize,
    pub bootstrap_gain: f64,
    /// R2 self-replication switch (0 = off). When on, the robot fleet
    /// staffs its own manufacturing, and the growth ceiling transitions
    /// from the HUMAN mobilization ceiling toward the MACHINE ceiling as
    /// autonomy rises — the "pure robotics is different from WWII" regime.
    pub robot_self_replication: f64,
    /// MACHINE mobilization ceiling (x/yr): the fastest a self-replicating
    /// industrial system can double, set by PHYSICAL throughput (a factory
    /// makes ~its own mass/yr; materials refining; the machines that make
    /// machines), NOT by human labor. Above WWII's 2.5x but finite.
    /// This is the parameter the robot-exponential argument turns on —
    /// dial it up to test faster self-replication.
    pub machine_ceiling: f64,
    /// Share of robot output reinvested into MORE manufacturing capacity
    /// vs consumed as labor (AI-2027's capacity-reinvestment split). High
    /// reinvest = faster self-replication, slower near-term labor effect.
    pub reinvest_share: f64,
    /// Fleet size (millions) at which manufacturing self-staffing reaches
    /// half — the Michaelis half-saturation of the human→machine autonomy
    /// transition. Below it, robots can't yet run their own factories at
    /// scale; well above it, the machine ceiling dominates.
    pub self_staff_half_m: f64,
    /// Grid draw per fielded robot (kW), continuous-duty equivalent. A
    /// billion-robot fleet competes with datacenter compute for the SAME
    /// constrained power buildout — the physical bound that keeps the
    /// self-replication exponential finite once the grid saturates.
    pub robot_kw_each: f64,
    // ---- self-replication FEEDBACK WEB (all gated by robot_self_replication;
    // set the master switch to 0 to recover the legacy robotics block) ----
    /// R-cost (reinforcing): robot-built robots are cheaper because the robot
    /// labor inside the factory is ~free — autonomy accelerates the Wright
    /// learning curve (extra effective doublings). Cheaper robots → shorter
    /// payback → more demand → more volume → cheaper still.
    pub learning_autonomy_gain: f64,
    /// R-energy (reinforcing): robots build their OWN generation. kW of new
    /// grid each reinvested robot-year constructs, added straight to the power
    /// stock (bypassing the human power-order pipeline) — this is the loop
    /// that RELIEVES the grid bind the fleet's own draw creates.
    pub energy_selfbuild_kw: f64,
    /// Rate limit (GW/yr) on robot-built generation — even a self-replicating
    /// fleet cannot stand up unlimited power per year (siting, grid, thermal).
    pub energy_buildout_ceiling_gw: f64,
    /// R-flywheel (reinforcing): robots build the fabs, datacenters, and power
    /// halls that compute lives in, so the chip/power capacity ceilings climb
    /// as autonomy rises → faster compute → smarter ASI → higher autonomy.
    pub asi_flywheel_gain: f64,
    /// R-materials (reinforcing): robots mine and refine their own inputs,
    /// relieving the metals cost pass-through as autonomy rises.
    pub materials_selfsupply_gain: f64,
    /// B-materials (balancing): the flip side — an exponential robot economy
    /// pressures ore grades and refining, raising delivered cost with the
    /// square root of fleet size. At extreme scale this wins over self-supply,
    /// putting a cost floor under the loop.
    pub materials_depletion_gain: f64,
    /// Fleet (millions) at which materials-depletion pressure reaches its
    /// sqrt-reference unit.
    pub materials_depletion_half_m: f64,
    /// B-maintenance (balancing): a huge deployed fleet absorbs a rising share
    /// of its own output just staying alive (upkeep, repair, replacement),
    /// throttling the reinvestment available for growth — diminishing returns
    /// to scale that keep the exponential finite. This is the drag on a
    /// HUMAN-run machine economy; see `maintenance_intelligence_relief`.
    pub maintenance_drag_gain: f64,
    /// Fleet (millions) at which maintenance drag reaches half its ceiling.
    pub maintenance_half_m: f64,
    /// Fraction of the maintenance drag that superintelligence dissolves as it
    /// diffuses (scales with ASI). Maintenance is exactly what intelligence
    /// attacks: predictive maintenance cuts unplanned downtime (McKinsey ~30-50%),
    /// robots repairing robots turns upkeep into cheap machine-labor rather than
    /// a headcount tax, and design-for-reliability raises MTBF. At full ASI the
    /// effective drag is (1 - relief)x the human-economy figure — a machine
    /// economy is NOT maintenance-taxed the way a human-run one is.
    pub maintenance_intelligence_relief: f64,
    pub robot_cost_2028_k: f64,
    pub robot_learning_rate: f64,
    pub robot_cost_floor_k: f64,
    pub robot_hew: f64,
    pub robot_attrition: f64,
    pub physical_addressable: f64,
    pub max_physical_displacement_rate: f64,
    // capital / margins / credit
    pub capex_gdp_cap: f64,
    pub internal_funding_share: f64,
    pub credit_gain: f64,
    pub debt_revenue_tolerance: f64,
    pub debt_amortization: f64,
    pub price_adjustment: f64,
    pub normal_margin: f64,
    pub rent_margin_slope: f64,
    pub margin_ceiling: f64,
    pub target_utilization: f64,
    pub ai_services_margin: f64,
    // R4 physical acceleration (post-singularity)
    pub asi_diffusion_years: f64,
    pub asi_delay_compression: f64,
    pub asi_ceiling_boost: f64,
    pub asi_integration_relief: f64,
    // capex behavior
    pub perception_smoothing: f64,
    pub momentum_gain: f64,
    pub demand_growth_base: f64,

    pub loops: Loops,
}

impl Default for Params {
    fn default() -> Self {
        Params {
            start_year: 2026,
            end_year: 2036,
            singularity_year: 2027,
            robotics_year: 2028,
            world_gdp: 115.0,
            cognitive_wage_bill: 28.0,
            physical_wage_bill: 34.0,
            wage_compression_cog_gain: 0.0, // off by default (satellite); ~0.5 is a live scenario
            wage_compression_phys_gain: 0.0,
            cognitive_workers_m: 950.0,
            physical_workers_m: 2400.0,
            base_gdp_growth: 0.03,
            productivity_passthrough: 0.35,
            transition_drag: 0.5,
            it_services_pool: 1.55,
            bpo_pool: 0.36,
            seat_saas_pool: 0.35,
            prof_info_pool: 0.45,
            it_services_beta: 0.9,
            bpo_beta: 1.25,
            saas_beta: 0.75,
            prof_info_beta: 0.35,
            ai_capex_2026: 0.65,
            compute_deprec: 0.25,
            silicon_share_of_capex: 0.55,
            chip_capacity_2026: 0.28,
            chip_base_growth: 0.30,
            chip_supply_gain: 1.6,
            chip_growth_ceiling: 0.85,
            chip_pipeline_stages: 2,
            hw_cost_decline: 0.15,
            ai_power_2026: 58.0,
            power_additions_2026: 30.0,
            transmission_gain: 0.0,      // off by default; ~1.0 is a live transmission-bound scenario
            transmission_growth: 0.26,   // ~26%/yr base transformer/HVDC ramp; below peak power demand growth
            power_base_growth: 0.08,
            power_supply_gain: 0.55,
            power_growth_ceiling: 0.40,
            power_pipeline_stages: 3,
            gw_per_compute_unit: 55.0,
            power_efficiency_gain: 0.12,
            power_equip_cost_per_gw: 0.0035,
            electricity_price_normal: 0.055,
            ai_hew_2026_m: 12.0,
            algo_eff_growth_pre: 2.5,
            singularity_boost: 2.0,
            recursive_years: 3,
            algo_eff_growth_post: 1.5,
            algo_eff_cap: 3000.0,
            adoption_halflife: 1.6,
            max_displacement_rate: 0.22,
            intelligence_returns_rho: 0.85,
            jevons_elasticity: 1.0,
            efficiency_jump_year: 0,
            efficiency_jump_size: 1.0,
            backlash_gain: 2.0,
            afford_gain: 0.4,
            society: society::SocietyParams::default(),
            demography: demography::DemographyParams::default(),
            space: space::SpaceParams::default(),
            macrofin: macrofin::MacroParams::default(),
            bio: bio::BioParams::default(),
            materials: materials::MaterialsParams::default(),
            energy: energy::EnergyParams::default(),
            food: food::FoodParams::default(),
            regions: regions::RegionParams::default(),
            food_tension_gain: 0.0,
            energy_price_gain: 0.0,
            equity_sentiment_gain: 0.0, // off by default (satellite); ~1.0 is a live boom-bust scenario
            wealth_effect_gain: 0.0,    // off by default; chains off the spine
            compute_governance_gain: 0.0, // off by default; ~0.5 is a licensing-regime scenario
            dread_shocks: Vec::new(),
            open_weight_share: 0.3,
            incident_year: 0,
            incident_dread: false,
            geo_shocks: Vec::new(),
            cognitive_demand_elasticity: 1.35,
            ai_task_price_rel: 0.04,
            addressable_cognitive: 0.85,
            robot_prod_2028_m: 0.12,
            component_capacity_2028: 0.14,
            component_base_growth: 0.45,
            component_supply_gain: 2.2,
            component_growth_ceiling: 1.4,
            component_pipeline_stages: 2,
            bootstrap_gain: 0.10,
            robot_self_replication: 1.0,
            // Doubling ~every 4.5 months — Carl Shulman's "existing industrial
            // equipment produces its own mass in a couple of months," and that
            // is the pre-superintelligence figure. 4x (6-month doubling) was the
            // conservative floor; 10x (~monthly) is the frontier case, tunable.
            machine_ceiling: 6.0,
            reinvest_share: 0.5,
            // Leading plants are ALREADY near-unmanned: FANUC's Oshino factory
            // runs robots-building-robots unattended for 720 hrs (30 days), and
            // Xiaomi's dark factory makes 10M phones/yr at ~81% automation with
            // essentially no floor workers. So the human headcount robots must
            // displace to self-staff is small (Epoch: ~a few thousand operators
            // per gigafactory making ~500k robots/yr), and each superintelligent
            // robot covers several of those roles — half-staffing arrives near
            // ~12M robots, not the 60M human-scale first cut.
            self_staff_half_m: 12.0,
            robot_kw_each: 2.0,
            learning_autonomy_gain: 0.5,
            energy_selfbuild_kw: 3.0,
            energy_buildout_ceiling_gw: 2000.0,
            asi_flywheel_gain: 0.3,
            materials_selfsupply_gain: 0.06,
            materials_depletion_gain: 0.05,
            materials_depletion_half_m: 1000.0,
            maintenance_drag_gain: 0.4,
            maintenance_half_m: 500.0,
            // Predictive maintenance alone cuts cost 10-40% and downtime 30-50%
            // (McKinsey/Deloitte); stack robots-repairing-robots (upkeep becomes
            // cheap machine-labor) and design-for-reliability (+20-40% lifespan,
            // MTBF already 40-100k hrs) and ~two-thirds of the growth-drag
            // dissolves at full ASI. The rest is the irreducible physical floor.
            maintenance_intelligence_relief: 0.65,
            robot_cost_2028_k: 50.0,
            robot_learning_rate: 0.22,
            robot_cost_floor_k: 8.0,
            robot_hew: 1.4,
            robot_attrition: 0.08,
            physical_addressable: 0.65,
            max_physical_displacement_rate: 0.15,
            capex_gdp_cap: 0.055,
            internal_funding_share: 0.65,
            credit_gain: 1.2,
            debt_revenue_tolerance: 1.5,
            debt_amortization: 0.90,
            price_adjustment: 0.6,
            normal_margin: 0.22,
            rent_margin_slope: 0.35,
            margin_ceiling: 0.62,
            target_utilization: 0.85,
            ai_services_margin: 0.35,
            asi_diffusion_years: 2.0,
            asi_delay_compression: 0.35,
            asi_ceiling_boost: 0.5,
            asi_integration_relief: 0.5,
            perception_smoothing: 0.5,
            momentum_gain: 0.5,
            demand_growth_base: 0.32,
            loops: Loops::default(),
        }
    }
}

// ---------------------------------------------------------------------------
// Pipeline: N-stage conserving material delay
// ---------------------------------------------------------------------------

#[derive(Clone, Debug)]
pub struct Pipeline {
    stages: Vec<f64>,
}

impl Pipeline {
    pub fn new(stages: usize, initial_flow: f64) -> Self {
        Pipeline { stages: vec![initial_flow; stages] }
    }

    /// Advance one year; returns delivered outflow.
    pub fn step(&mut self, inflow: f64) -> f64 {
        let mut carry = inflow;
        for slot in self.stages.iter_mut() {
            std::mem::swap(slot, &mut carry);
        }
        carry
    }

    /// Advance one year with post-singularity acceleration: after the
    /// normal step, pull `extra` (0..=1) of each stage's remaining material
    /// forward one slot (the last stage's fraction is delivered). Conserving.
    pub fn step_accel(&mut self, inflow: f64, speedup: f64) -> f64 {
        let mut out = self.step(inflow);
        let extra = (speedup - 1.0).clamp(0.0, 1.0);
        if extra > 0.0 {
            let n = self.stages.len();
            for i in (0..n).rev() {
                let mv = self.stages[i] * extra;
                self.stages[i] -= mv;
                if i == n - 1 {
                    out += mv;
                } else {
                    self.stages[i + 1] += mv;
                }
            }
        }
        out
    }

    pub fn in_transit(&self) -> f64 {
        self.stages.iter().sum()
    }

    pub fn first_stage(&self) -> f64 {
        self.stages.first().copied().unwrap_or(0.0)
    }
}

fn logistic(x: f64) -> f64 {
    1.0 / (1.0 + (-x).exp())
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "lowercase"))]
pub enum Binding {
    Power,
    Chips,
    Capital,
    Demand,
}

#[derive(Clone, Debug)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct Pools {
    pub ai_services: f64,
    pub silicon: f64,
    pub ip_tolls: f64,
    pub dc_infra: f64,
    pub power_equipment: f64,
    pub electricity: f64,
    pub robots: f64,
    pub robot_components: f64,
    pub robot_services: f64,
    pub it_services: f64,
    pub bpo: f64,
    pub seat_saas: f64,
    pub prof_info: f64,
    pub human_cognitive_wages: f64,
    pub human_physical_wages: f64,
    pub gdp_index: f64,
}

#[derive(Clone, Debug)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct Profits {
    pub ai_services: f64,
    pub silicon: f64,
    pub ip_tolls: f64,
    pub dc_infra: f64,
    pub power_equipment: f64,
    pub electricity: f64,
    pub robots: f64,
    pub robot_components: f64,
    pub robot_services: f64,
    pub it_services: f64,
    pub bpo: f64,
    pub seat_saas: f64,
    pub prof_info: f64,
}

#[derive(Clone, Debug)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct YearState {
    pub year: i32,
    pub binding: Binding,
    pub ai_capex: f64,
    pub compute_stock: f64,
    pub algo_eff: f64,
    pub ai_power_gw: f64,
    pub power_utilization: f64,
    pub chip_utilization: f64,
    pub silicon_margin: f64,
    pub power_margin: f64,
    pub component_margin: f64,
    pub electricity_price: f64,
    pub ai_hew_m: f64,
    pub cog_displacement: f64,
    pub cognitive_task_index: f64,
    pub adoption_friction: f64,
    pub adoption_level: f64,
    pub robot_prod_m: f64,
    pub robot_fleet_m: f64,
    pub robot_cost_k: f64,
    pub component_capacity_m: f64,
    /// Critical-input Liebig ceiling on robot production this year (M/yr);
    /// f64::INFINITY when the materials layer is off or nothing binds.
    pub materials_ceiling_m: f64,
    /// Name of the binding critical input ("precision_reducers", etc.).
    pub materials_binding: String,
    // ---- energy generation mix ----
    pub firm_power_gw: f64,
    pub solar_gw: f64,
    pub battery_gwh: f64,
    pub clean_power_share: f64,
    pub electricity_cost_index: f64,
    // ---- food ----
    pub food_price_index: f64,
    pub food_unrest: f64,
    // ---- regional blocs (US, China, EU order) ----
    pub bloc_capability: Vec<f64>,
    pub bloc_stress: Vec<f64>,
    /// Per-bloc fracture/regime-shift hazard (US, China, EU). China's rises
    /// nonlinearly once suppressed stress crosses the brittleness threshold.
    pub bloc_fracture_risk: Vec<f64>,
    pub china_us_capability_gap: f64,
    pub west_capability_share: f64,
    pub phys_displacement: f64,
    pub sector_debt: f64,
    pub credit_multiplier: f64,
    pub perceived_growth: f64,
    pub queue_ratio: f64,
    pub capacity_glut: f64,
    /// AI-capex reflexivity stock (1.0 = neutral; >1 euphoria, <1 Minsky bust).
    /// Frozen at 1.0 unless `equity_sentiment_gain > 0`.
    pub equity_sentiment: f64,
    pub ip_toll_margin: f64,
    pub gdp: f64,
    // society layer (end-of-year stocks; neutral defaults when layer off)
    pub sentiment: f64,
    pub reg_enforcement: f64,
    pub transfer_share: f64,
    pub labor_power: f64,
    pub inst_trust: f64,
    pub consumer_trust: f64,
    // demography layer (end-of-year; legacy constants when layer off)
    pub blocked_entrants_m: f64,
    pub visible_disp_rate: f64,
    pub tension: f64,
    pub solidarity: f64,
    pub migration_openness: f64,
    pub cog_pool_m: f64,
    pub phys_pool_m: f64,
    /// Land diagnostics: autonomization index = investment share of
    /// output over wage-financed share (teleoplexy/means-ends reversal
    /// made measurable; historical base rate: every production-for-
    /// production regime — Soviet, China 45% inv/GDP, railroads —
    /// reverted, but none contained recursive intelligence).
    pub autonomization_index: f64,
    /// Meltdown ratio: economic change rate / political response rate.
    /// Land predicts divergence; the society layer predicts
    /// spike-then-collapse. Regulatory-latency history (web->GDPR 23yr,
    /// social->acts 15yr, ChatGPT->AI Act 1.5yr) favors the thermostat.
    pub meltdown_ratio: f64,
    // bio/cyber layer
    pub bio_hazard: f64,
    pub cyber_hazard: f64,
    pub drug_pool_b: f64,
    /// Bio optionality pools ($B), computed by the bio layer (audit C14: previously
    /// returned but discarded). Observability only — not fed back into the core.
    pub longevity_pool_b: f64,
    pub bci_pool_b: f64,
    pub bio_materials_pool_b: f64,
    // macro-finance layer
    pub long_rate: f64,
    pub gov_debt_gdp: f64,
    pub debt_service: f64,
    // space layer
    pub orbital_gw_equiv: f64,
    pub launch_cost_per_kg: f64,
    pub launch_capacity_tpy: f64,
    pub pools: Pools,
    pub profits: Profits,
}

// ---------------------------------------------------------------------------
// Simulation
// ---------------------------------------------------------------------------

fn power_orders(p: &Params, power_margin: f64, perceived_growth: f64,
                current_rate: f64, ceiling_mult: f64) -> f64 {
    let excess = (power_margin - p.normal_margin).max(0.0);
    let growth = (p.power_base_growth
        + p.loops.b1_supply_response * p.power_supply_gain * excess
        + 0.3 * (perceived_growth - 0.3).max(0.0))
        .min(p.power_growth_ceiling * ceiling_mult);
    current_rate * (1.0 + growth)
}

pub fn simulate(p: &Params) -> Vec<YearState> {
    let l = &p.loops;

    let mut compute_stock = 1.0_f64;
    let mut algo_eff = 1.0_f64;
    let mut ai_power = p.ai_power_2026;
    let mut transmission_capacity = p.ai_power_2026; // deliverable-power ceiling stock (transformers/HVDC)
    let mut chip_capacity = p.chip_capacity_2026;
    let mut ip_capacity = chip_capacity * 0.18;
    let mut component_capacity = 0.0_f64;
    let mut robot_fleet = 0.0_f64;
    let mut cum_robots = 0.02_f64;
    let mut robot_cost = p.robot_cost_2028_k;
    // Last year's manufacturing-autonomy fraction — the self-replication
    // feedback web's cross-timestep coupling: robots that staffed factories,
    // built power halls, and stood up fabs LAST year raise this year's
    // ceilings, grid, and cost curve (the loops that close a year apart).
    let mut autonomy_prev = 0.0_f64;
    // Cumulative ASI-weighted years since singularity — drives how far the
    // materials-substitution/design-out program has progressed (RE-free motors,
    // cycloidal/QDD reducers, thrifting) against the critical-input chokepoints.
    let mut asi_years = 0.0_f64;
    // Energy / food / regions satellite layers (supply side of the power
    // constraint; food↔energy↔tension chain; US/China/EU divergence).
    let mut materials_state = materials::MaterialsState::new(&p.materials);
    let mut prev_robot_demand = p.robot_prod_2028_m;
    let mut energy_state = energy::EnergyState::new(&p.energy);
    let mut food_state = food::FoodState::new();
    let mut region_state = regions::RegionState::new(&p.regions);
    let mut food_unrest_prev = 0.0_f64; // one-year-lagged food→tension coupling
    let mut energy_cost_index_prev = 1.0_f64; // one-year-lagged energy→core price coupling (C3)
    let mut wage_index_cog = 1.0_f64; // wage-compression stock (1.0 = no compression)
    let mut wage_index_phys = 1.0_f64;
    let mut equity_sentiment = 1.0_f64; // AI-capex bubble/bust reflexivity stock (1.0 = neutral)
    let mut prev_adopt_region = 0.08_f64;
    #[allow(unused_assignments)]
    let mut human_cog_m = p.cognitive_workers_m;
    let mut phys_workers_m = p.physical_workers_m;
    let mut gdp = p.world_gdp;
    let mut sector_debt = 0.0_f64;
    let mut perceived_growth = p.demand_growth_base;
    let mut last_capex = p.ai_capex_2026 * 0.8;
    let mut last_desired = p.ai_capex_2026;
    let mut prev_disp = 0.0_f64;
    let mut prev_disp_macro = 0.0_f64;
    let mut prev_adopt = 0.08_f64;

    // Society layer state (endogenous political economy).
    let soc_on = l.society_layer > 0.0;
    let mut soc = SocietyState::new(&p.society);
    let mut prev_adopt_soc = 0.0_f64;
    let mut dread_armed = false;

    // Demography: dynamic pools + political signal filter. Steps BEFORE
    // society each year; prior-year outputs modulate this year's loops.
    let demo_on = l.d_demography > 0.0;
    let mut demo = DemographyState::new(
        &p.demography, p.cognitive_workers_m, p.physical_workers_m);
    let mut demo_out: Option<DemographyOutputs> = None;

    // Space: launch learning + orbital compute.
    let mut space = SpaceState::new(&p.space);
    // Bio/cyber: drug pool, hazards, healthcare deflation, shadow pools.
    let bio_on = p.bio.bio_layer > 0.0;
    let mut biostate = BioState::new(&p.bio);
    let mut bio_out: Option<BioOutputs> = None;

    // Macro-finance: endogenous long rate + sovereign snowball (B11).
    let macro_on = l.b11_endogenous_rates > 0.0;
    let mut macrost = MacroState::new(&p.macrofin);
    let mut macro_out: Option<macrofin::MacroOutputs> = None;

    // Geopolitics: metals index is mean-reverting (half-life ~2.5yr);
    // onshoring scares boost the supply response for 4 years.
    let mut metals_index = 1.0_f64;
    let mut onshoring_until = i32::MIN;
    let mut invaded = false;
    let mut gw_per_unit = p.gw_per_compute_unit;
    let mut power_jevons_mult = 1.0_f64; // persistent post-efficiency-jump power scaler

    let mut power_pipe = Pipeline::new(p.power_pipeline_stages, p.power_additions_2026);
    let mut chip_pipe = Pipeline::new(p.chip_pipeline_stages,
                                      chip_capacity * p.chip_base_growth);
    let mut ip_pipe = Pipeline::new(p.chip_pipeline_stages,
                                    ip_capacity * p.chip_base_growth);
    let mut comp_pipe = Pipeline::new(p.component_pipeline_stages, 0.0);

    let mut silicon_margin = p.normal_margin + 0.10;
    let mut prev_ip_util = 1.05_f64;
    // the ordering RATE is its own stock — never read back from the pipeline,
    // whose stages are mutated by acceleration (bug found via the fizzle>
    // baseline capex anomaly)
    let mut power_order_rate = p.power_additions_2026;
    let mut ip_toll_margin = p.normal_margin + 0.15;
    let mut power_margin = p.normal_margin + 0.08;
    let mut component_margin = p.normal_margin;

    let mut out: Vec<YearState> = Vec::new();

    for year in p.start_year..=p.end_year {
        // ---- space: step on prior-year power rents (B11 gate) ----
        let power_rent_index = ((power_margin - p.normal_margin)
            / (p.margin_ceiling - p.normal_margin))
            .clamp(0.0, 1.0);
        space.step(&p.space, year, power_rent_index, l.r5_launch_learning);

        // ---- bio/cyber: drug pool, hazards, healthcare deflation ----
        let prev_adopt_bio = out.last().map_or(0.08, |st| st.adoption_level);
        let bfx = bio::shocks::effects_for_year(&p.dread_shocks, year);
        if bio_on {
            // C6: a mass-casualty bio event arms the mandatory synthesis-screening
            // ratchet — the balancing loop that re-closes the synthesis-access
            // gate. Previously `arm_screening_mandate` was never called, leaving
            // the biorisk subsystem a pure runaway gate with no counter-force.
            if bfx.arm_screening {
                biostate.arm_screening_mandate();
            }
            bio_out = Some(biostate.step(
                &p.bio,
                algo_eff,
                prev_adopt_bio,
                (last_capex / p.ai_capex_2026).min(3.0),
                p.open_weight_share,
            ));
        }

        // ---- geopolitical shock effects for this year ----
        let gfx = geopolitics::effects_for_year(&p.geo_shocks, year);
        if gfx.chip_destruction > 0.0 {
            chip_capacity *= 1.0 - gfx.chip_destruction;
            ip_capacity *= 1.0 - gfx.chip_destruction * 0.5;
            invaded = true;
        }
        if gfx.onshoring {
            onshoring_until = onshoring_until.max(year + 4);
        }
        // Metals index chases the shock target, mean-reverts otherwise.
        metals_index += if gfx.metals_target > metals_index {
            0.8 * (gfx.metals_target - metals_index)
        } else {
            0.25 * (1.0 - metals_index) // half-life ~2.5yr
        };
        let onshoring_boost = if year <= onshoring_until { 1.5 } else { 1.0 };
        let t_sing = year - p.singularity_year;

        // Efficiency discontinuity (DeepSeek-class): a >=10x algorithmic
        // efficiency jump permanently scales NET power demand by
        // jump^(jevons-1). jevons=1 => neutral (demand fills efficiency,
        // legacy); jevons<1 => net power demand falls (the power-sleeve
        // bear case, DeepSeek Jan-2025); jevons>1 => commodity-Jevons rise.
        if year == p.efficiency_jump_year && p.efficiency_jump_size > 1.0 {
            power_jevons_mult *= p.efficiency_jump_size.powf(p.jevons_elasticity - 1.0);
        }

        // ---- R1: recursive AI (saturating) ----
        if year > p.start_year {
            let g = if year <= p.singularity_year {
                p.algo_eff_growth_pre
            } else if t_sing <= p.recursive_years {
                let boost = 1.0 + (p.singularity_boost - 1.0) * l.r1_recursive_ai;
                p.algo_eff_growth_pre * boost
            } else {
                p.algo_eff_growth_post
            };
            let headroom = (1.0 - algo_eff / p.algo_eff_cap).max(0.0);
            algo_eff *= 1.0 + (g - 1.0) * headroom;
        }

        // ---- demand side: adoption with B2 + B3 ----
        let recent_disp_rate = if out.len() >= 2 {
            (out[out.len() - 1].cog_displacement
                - out[out.len() - 2].cog_displacement).max(0.0)
        } else if !out.is_empty() {
            out[out.len() - 1].cog_displacement
        } else {
            0.0
        };
        // B2 gain is endogenous when the society layer is on: a pulse
        // shaped by sentiment, labor power, transfers, and trust —
        // peaking with the displacement rate and fading after (design
        // doc §5.1) — instead of a constant.
        let mut soc_mult = if soc_on {
            soc.backlash_multiplier(&p.society, recent_disp_rate)
        } else {
            1.0
        };
        if let Some(d) = &demo_out {
            // Grievance redirection: scapegoating routes backlash away
            // from AI firms (conserved flow — pro-adoption short-run,
            // socially corrosive via the unrest multiplier below).
            soc_mult *= 1.0 - d.backlash_redirect.min(0.5);
        }
        let friction = 1.0 + l.b2_backlash * p.backlash_gain * recent_disp_rate * soc_mult;

        let btl_price = if let Some(prev) = out.last() {
            let b = prev.power_utilization.max(prev.chip_utilization);
            ((b - p.target_utilization).max(0.0) / (1.0 - p.target_utilization))
                .min(1.5)
        } else {
            0.4
        };
        let afford = 1.0 + l.b3_affordability * p.afford_gain * btl_price;

        let pre_ramp = (0.08 * 1.6_f64.powi(year - p.start_year)).min(0.28);
        let adopt_raw = if t_sing < 0 {
            pre_ramp
        } else {
            let k = 3.0_f64.ln() / (p.adoption_halflife * friction);
            logistic(k * (t_sing as f64 - p.adoption_halflife * friction))
                .max(pre_ramp)
                .max(0.10)
        };
        // Regulation slows the adoption RATE (GDPR: -25% at full
        // enforcement) and consumer trust caps the LEVEL (B10); neither
        // can un-adopt, so adoption stays a ratchet.
        let adopt = if soc_on {
            let capped = adopt_raw.min(soc.adoption_ceiling(&p.society));
            (prev_adopt_soc
                + (capped - prev_adopt_soc).max(0.0)
                    * soc.adoption_rate_mult(&p.society))
                .max(prev_adopt_soc)
        } else {
            adopt_raw
        };
        prev_adopt_soc = adopt;

        // Concave returns to intelligence: anchored at t0 where
        // compute_stock * algo_eff = 1, so rho only shapes GROWTH.
        let ai_hew_raw = p.ai_hew_2026_m
            * (compute_stock * algo_eff).max(1e-12).powf(p.intelligence_returns_rho);
        let price_ratio = if t_sing >= 0 { p.ai_task_price_rel * afford } else { 0.25 };
        let task_expansion = price_ratio
            .powf(-(p.cognitive_demand_elasticity - 1.0) * 0.35)
            .min(6.0);
        let cognitive_task_index = 1.0 + (task_expansion - 1.0) * adopt;
        let addressable = p.cognitive_workers_m * p.addressable_cognitive;
        let demand_hew = addressable * adopt * cognitive_task_index;
        let ai_hew = ai_hew_raw.min(demand_hew);

        let disp_target = (ai_hew / cognitive_task_index.max(1e-9)).min(addressable)
            / p.cognitive_workers_m;
        let mut disp = (disp_target * (adopt * 1.4).min(1.0))
            .min(prev_disp + p.max_displacement_rate / friction);
        disp = disp.max(prev_disp);
        prev_disp = disp;
        human_cog_m = p.cognitive_workers_m * (1.0 - disp);

        // ---- R4: physical acceleration factor (0 pre-singularity,
        // ramping toward 1 as ASI diffuses into engineering practice) ----
        let asi = if t_sing >= 0 {
            l.r4_physical_acceleration
                * (1.0 - (-((t_sing as f64) + 1.0) / p.asi_diffusion_years).exp())
        } else {
            0.0
        };
        asi_years += asi; // cumulative ASI-weighted years (materials substitution clock)
        // R-flywheel (robots build the physical layer compute lives in): last
        // year's autonomous fleet stood up fabs, datacenters, and power halls,
        // so this year's construction speedup and capacity ceilings are higher.
        // Closes the loop compute → ASI → autonomy → more compute infra.
        let robot_infra_boost =
            p.robot_self_replication * p.asi_flywheel_gain * autonomy_prev;
        let speedup = (1.0 + asi * p.asi_delay_compression) * (1.0 + 0.5 * robot_infra_boost);
        let ceiling_mult = (1.0 + asi * p.asi_ceiling_boost) * (1.0 + robot_infra_boost);

        // ---- R3: capex desire from perceived demand ----
        let mut demand_signal_growth = p.demand_growth_base;
        if t_sing >= 0 {
            demand_signal_growth += 1.6 * (adopt - prev_adopt).max(0.0) + 0.5 * adopt;
        }
        if soc_on {
            // Precautionary savings: elevated sentiment cuts consumption
            // before displacement does (GFC +4pp saving rate).
            demand_signal_growth -= soc.precautionary_drag(&p.society);
        }
        let adopt_delta = (adopt - prev_adopt).max(0.0);
        prev_adopt = adopt;
        perceived_growth += p.perception_smoothing
            * (demand_signal_growth - perceived_growth);
        let herd = l.r3_capex_momentum * p.momentum_gain * perceived_growth.max(0.0);
        // ---- Financial-fragility spine: AI-capex bubble/bust reflexivity (gated) ----
        // Update the equity-sentiment stock from LAST year's realized glut and margin
        // (lagged, so no in-loop ordering hazard). Asymmetric Minsky dynamics: a
        // capacity glut past 1.3 cracks sentiment fast toward a fear floor; otherwise
        // it builds slowly on AI-complex profitability + demand momentum.
        // equity_sentiment_gain = 0 (default) leaves the stock frozen at 1.0.
        if p.equity_sentiment_gain > 0.0 {
            let prev_glut = out.last().map_or(0.9, |s| s.capacity_glut);
            if prev_glut > 1.3 {
                let floor = (1.0 - 1.2 * (prev_glut - 1.3)).max(0.35);
                equity_sentiment += 0.6 * (floor - equity_sentiment); // fast crack
            } else {
                let boom = 1.0
                    + 0.6 * (silicon_margin - p.normal_margin).max(0.0)
                    + 0.3 * perceived_growth.max(0.0);
                equity_sentiment += 0.2 * (boom - equity_sentiment); // slow build
            }
        }
        // Deviation actually applied (0 when the spine is gated off → byte-identical).
        let es_dev = p.equity_sentiment_gain * (equity_sentiment - 1.0);
        // B3 closure: bottleneck prices throttle desired capex growth.
        // Desire base avoids the absorbing zero-capex state (round-2 fix 2).
        let desire_base = last_capex.max(0.3 * last_desired);
        let desired_capex = desire_base * (1.0 + (perceived_growth + herd) / afford)
            * gfx.demand_mult
            * (1.0 + es_dev).max(0.2); // sentiment amplifies the boom, cuts the bust
        last_desired = desired_capex;

        // ---- B4: credit ----
        let ai_revenue_proxy = (out.last().map_or(0.02, |s| s.pools.ai_services)
            + 0.25 * last_capex)
            .max(0.05);
        let leverage = sector_debt / ai_revenue_proxy.max(1e-9);
        // Society-layer injections into B4 (the ONLY financial channel):
        // sovereign crowding-out from debt-financed transfers plus the R7
        // regulatory-cost spiral (armed only by a dread incident).
        let soc_credit = if soc_on && !macro_on {
            // when B11 is on, the sovereign-crowding channel lives in the
            // macro layer's risk-free-rate injection (no double-count)
            soc.credit_injection(&p.society, dread_armed)
        } else if soc_on {
            // keep only the R7 regulatory-spiral part, not the crowding part
            // (crowding lives in the macro layer's risk-free-rate injection)
            soc.credit_spiral(dread_armed)
        } else {
            0.0
        };
        let macro_credit = macro_out.as_ref().map_or(0.0, |m| m.credit_injection);
        // Reflexive credit: buoyant sentiment eases spreads (es_dev>0 shrinks the
        // denominator → higher credit_mult), a Minsky bust tightens them into a
        // crunch (es_dev<0 widens it). Floored so the denominator stays positive in
        // an extreme boom. es_dev = 0 when the spine is gated off → byte-identical.
        let credit_denom = (1.0
            + l.b4_credit
                * (p.credit_gain * (leverage - p.debt_revenue_tolerance).max(0.0)
                    + soc_credit
                    + macro_credit
                    + gfx.spread
                    + bfx.spread)
            - es_dev * l.b4_credit * 2.0)
            .max(0.2);
        let credit_mult = 1.0 / credit_denom;

        // ---- constraints ----
        let hw_cost_index = (1.0 - p.hw_cost_decline).powi(year - p.start_year);
        let cost_per_unit = (p.ai_capex_2026 / 0.80) * hw_cost_index;

        // deliver chip + ip capacity at the START of the year (same-year
        // convention as power); orders use last year's margins.
        let excess_margin = (silicon_margin - p.normal_margin).max(0.0);
        // Onshoring scares boost the supply response x1.5 for 4 years
        // (China WFE localization tripled post-Oct-2022); post-invasion
        // rebuild is EUV-capped at ~18%/yr regardless of price signal.
        // DEFERRED (audit B4): leading-edge fab expansion is physically the
        // HARDEST capacity to accelerate (ASML EUV output ~50-60/yr, 3-5yr fab
        // builds → ~20-45%/yr even under a strong price signal), yet this uses the
        // full compute-flywheel `ceiling_mult` and a 0.85 base ceiling, licensing
        // an absurd >150%/yr ASI-boosted fab growth. A trial fix (ceiling 0.45 +
        // a halved fab_ceiling_mult) is correct in isolation but its baseline
        // effect is to dampen the model's CORE overshoot signature — peak capacity
        // glut 1.53 → 1.28 — below the established 1.3 glut-detection convention
        // used by several backtest/behavior conclusion tests (bust_lag,
        // silicon_glut_emerges). Compute is power-gated so the upside is low while
        // the repricing of the validated overshoot/backtest envelope is real; that
        // is a deliberate call for the model owner, not an overnight threshold
        // retune. Revisit with the user: retune {chip_growth_ceiling, fab boost,
        // the 1.3 glut convention} jointly against the historical [1.15,3.5] band.
        let mut chip_growth = (p.chip_base_growth
            + l.b1_supply_response * p.chip_supply_gain * excess_margin
                * onshoring_boost)
            .min(p.chip_growth_ceiling * ceiling_mult);
        if invaded {
            // Post-invasion fab rebuild is capped at ~18%/yr while human-paced,
            // but the latch must not be PERMANENT: as ASI diffuses it rebuilds
            // fabs faster (the model's own premise), so the cap recovers toward
            // the boosted ceiling rather than pinning growth for all time.
            chip_growth = chip_growth.min((0.18 + asi * 0.5).min(p.chip_growth_ceiling * ceiling_mult));
        }
        let chip_delivery = chip_pipe.step_accel(chip_capacity * chip_growth, speedup);
        chip_capacity += chip_delivery;
        // The IP toll's pace is strategic: a monopolist expands only under
        // excess demand and never into slack (defending price is what market
        // power means). ASI acceleration does not apply to it either.
        let ip_expand = p.chip_base_growth
            * ((prev_ip_util - 0.95) / 0.40).clamp(0.0, 1.0);
        let ip_delivery = ip_pipe.step(ip_capacity * ip_expand);
        ip_capacity += ip_delivery;

        let chips_cap = chip_capacity * gfx.chip_mult / p.silicon_share_of_capex;
        if year > p.start_year {
            gw_per_unit *= 1.0 - p.power_efficiency_gain;
        }
        let orders = power_orders(p, power_margin, perceived_growth,
                                  power_order_rate,
                                  1.0 + asi * p.asi_ceiling_boost * 0.5);
        power_order_rate = orders;
        // Shock haircut on energization (blockade: no GPUs to fill halls;
        // the lost flow is destroyed, not deferred — war losses).
        let power_additions = power_pipe.step_accel(orders, speedup) * gfx.power_mult;
        // A fielded robot fleet draws the SAME constrained grid the datacenters
        // are racing to build. At a billion robots this is TW-scale and becomes
        // the physical bound on the self-replication exponential (last year's
        // fleet; the draw is subtracted from headroom compute competes over).
        // Units: robot_fleet is in MILLIONS of robots, robot_kw_each is kW per
        // robot, so total draw in GW = fleet_millions × kW (the 1e6 robots and
        // the kW→GW 1e-6 cancel). 8B robots × 2 kW = ~16 TW.
        let robot_power_gw = robot_fleet * p.robot_kw_each;
        // R-energy (robots build their own generation): last year's autonomous
        // fleet stood up power, added straight to the grid stock, bypassing the
        // human power-order pipeline. This is the loop that RELIEVES the draw
        // above — a self-replicating fleet ends up NET-powering itself. Rate-
        // limited: siting/thermal cap how much generation goes up per year.
        let robot_power_built_gw = (p.robot_self_replication * autonomy_prev
            * p.reinvest_share * robot_fleet * p.energy_selfbuild_kw)
            .min(p.energy_buildout_ceiling_gw);
        // NOTE (audit A7, DEFERRED): this subtracts the full pre-depreciation
        // compute draw, slightly over-tightening power vs power_demand_gw's
        // depreciated treatment. The one-line fix (multiply by (1-compute_deprec))
        // is verified-correct in isolation, but it interacts adversely with the
        // robot power gate below: freeing compute power lets compute consume more
        // grid, and the gate hands robots only the RESIDUAL (grid - compute_draw),
        // starving them of the ~1 GW they need when compute is itself power-bound
        // — halving the mid-2030s robot fleet and masking the embargo/component
        // gates. Ship only after reworking the gate so robot demand joins grid
        // ORDERS rather than taking the residual.
        let power_headroom = (ai_power + robot_power_built_gw + space.orbital_gw_equiv
            + power_additions
            - compute_stock * gw_per_unit * power_jevons_mult
            - robot_power_gw)
            .max(0.0);
        let power_cap = (power_headroom / gw_per_unit) * cost_per_unit;
        let capital_cap = gdp * p.capex_gdp_cap * credit_mult;

        let caps = [
            (Binding::Chips, chips_cap),
            (Binding::Power, power_cap),
            (Binding::Capital, capital_cap),
            (Binding::Demand, desired_capex),
        ];
        let (mut binding, mut ai_capex) = (Binding::Chips, chips_cap);
        for &(b, v) in &caps[1..] {
            if v < ai_capex {
                binding = b;
                ai_capex = v;
            }
        }
        let queue_ratio = (desired_capex
            / chips_cap.min(power_cap).min(capital_cap).max(1e-9))
            .min(50.0);
        let capacity_glut = (chip_capacity
            / (desired_capex * p.silicon_share_of_capex).max(1e-9))
            .min(50.0);

        sector_debt = sector_debt * p.debt_amortization
            + (ai_capex * (1.0 - p.internal_funding_share)).max(0.0);

        let pre_stock = compute_stock;
        // Compute-governance throttle (gated): a licensing/compute-cap regime that
        // tightens as frontier capability rises, cutting compute added per capex
        // dollar at the SOURCE of the R1 flywheel. gain 0 => throttle 1 => baseline.
        let governance_throttle = 1.0 - p.compute_governance_gain * asi.clamp(0.0, 1.0);
        let units_added = ai_capex / cost_per_unit * governance_throttle;
        compute_stock = compute_stock * (1.0 - p.compute_deprec) + units_added;
        // Transmission/HVDC delivery lag (gated): transformers/HVDC converters ramp
        // at a lead-time-bound rate; when the gain is on, generation that outruns the
        // transmission stock cannot energize — capping the usable additions and
        // stranding the excess as built-but-undeliverable generation. gain 0 →
        // deliverable == power_additions → baseline byte-identical.
        // Transmission capacity compounds (more transformer/HVDC factories) with a
        // modest ASI lift, but at a rate kept BELOW peak AI-power demand growth so it
        // lags and binds in the boom — the lead-time bottleneck.
        transmission_capacity *= 1.0 + p.transmission_growth * (1.0 + 0.25 * asi);
        let total_additions = power_additions + robot_power_built_gw;
        let deliverable_additions = if p.transmission_gain > 0.0 {
            let headroom = (transmission_capacity - ai_power).max(0.0);
            let capped = total_additions.min(headroom);
            total_additions + p.transmission_gain.clamp(0.0, 1.0) * (capped - total_additions)
        } else {
            total_additions
        };
        ai_power += deliverable_additions;
        let used_power = (compute_stock * gw_per_unit * power_jevons_mult).min(ai_power);

        // ---- utilizations, prices, margins ----
        let chip_utilization = (desired_capex * p.silicon_share_of_capex
            / chip_capacity.max(1e-9))
            .min(1.35);
        // IP demand is the same 18% slice of silicon flow its capacity
        // serves (round-2 review fix).
        let ip_utilization = (desired_capex * p.silicon_share_of_capex * 0.18
            / ip_capacity.max(1e-9))
            .min(1.35);
        prev_ip_util = ip_utilization;
        let power_demand_gw = (pre_stock * (1.0 - p.compute_deprec) * gw_per_unit
            + (desired_capex / cost_per_unit) * gw_per_unit)
            * power_jevons_mult;
        let power_utilization = (power_demand_gw
            / (ai_power + space.orbital_gw_equiv).max(1e-9))
            .min(1.35);

        let margin_from = |u: f64, gain_class: f64| -> f64 {
            let excess = (u - p.target_utilization).max(0.0)
                / (1.0 - p.target_utilization);
            (p.normal_margin + p.rent_margin_slope * excess.min(2.0) * gain_class)
                .min(p.margin_ceiling)
        };

        let pa = p.price_adjustment;
        silicon_margin += pa * (margin_from(chip_utilization, 0.9) - silicon_margin);
        ip_toll_margin += pa * (margin_from(ip_utilization, 0.9) - ip_toll_margin);
        power_margin += pa * (margin_from(power_utilization, 1.0) - power_margin);
        let electricity_price = p.electricity_price_normal
            * (1.0 + 1.2 * (((power_utilization - p.target_utilization).max(0.0))
                / (1.0 - p.target_utilization))
                .min(2.0));
        // C3: blend the energy layer's generation cost_index (last year's, to
        // avoid reordering the satellite section) into the AI-sector electricity
        // price. The scarcity term above prices datacenter UTILIZATION; the energy
        // layer prices GENERATION — as solar+battery Wright's law pulls cost_index
        // below 1.0, cheap clean power relieves the effective price the sector
        // pays. Gated: energy_price_gain = 0 (default) leaves the price untouched.
        let electricity_price = if p.energy.enabled > 0.0 && p.energy_price_gain > 0.0 {
            let g = p.energy_price_gain.clamp(0.0, 1.0);
            electricity_price * ((1.0 - g) + g * energy_cost_index_prev)
        } else {
            electricity_price
        };

        // ---- robotics ----
        let mut robot_prod = 0.0;
        let mut mat_binding: &'static str = "none";
        let mut mat_ceiling_m = f64::INFINITY;
        // Price actually PAID this year (shock premia included); the
        // Wright's-law learning state stays on the clean cost curve.
        let mut robot_cost_paid = robot_cost;
        if year >= p.robotics_year {
            if component_capacity == 0.0 {
                component_capacity = p.component_capacity_2028;
            }
            let comp_excess = (component_margin - p.normal_margin).max(0.0);

            // ---- R2 self-replication: the human→machine ceiling transition ----
            // The WWII 2.5x/yr ceiling is a HUMAN mobilization ceiling — it caps
            // how fast people can stand up new factories. Once the fleet is large
            // enough to STAFF its own manufacturing (and superintelligence directs
            // it there), that constraint dissolves: the binding ceiling migrates
            // toward the finite MACHINE ceiling (physical throughput of a factory
            // reproducing its own mass), which is higher but not unbounded.
            // Autonomy saturates in fleet size and is gated by ASI focus, so it is
            // ~0 before superintelligence and climbs as robots build robots.
            let mfg_autonomy = (p.robot_self_replication
                * asi
                * (robot_fleet / (robot_fleet + p.self_staff_half_m)))
                .clamp(0.0, 1.0);
            let eff_growth_ceiling = p.component_growth_ceiling
                + (p.machine_ceiling - p.component_growth_ceiling) * mfg_autonomy;

            // B-maintenance (balancing): a large deployed fleet spends a rising
            // share of its own output just staying alive — upkeep, repair, and
            // replacement — so the reinvestment actually available for GROWTH
            // shrinks with scale. But maintenance is exactly what intelligence
            // attacks: predictive maintenance cuts unplanned downtime, robots
            // repair robots (upkeep becomes cheap machine-labor, not a headcount
            // tax), and design-for-reliability raises MTBF. So the drag
            // COEFFICIENT falls as ASI diffuses — a machine economy is not
            // maintenance-taxed the way a human-run one is. The remaining drag is
            // the irreducible physical floor (parts wear out, entropy is real).
            let maint_relief = 1.0 - p.maintenance_intelligence_relief * asi;
            let maint_fraction = p.robot_self_replication * p.maintenance_drag_gain
                * maint_relief
                * (robot_fleet / (robot_fleet + p.maintenance_half_m));
            let eff_reinvest = p.reinvest_share * (1.0 - maint_fraction);

            let bootstrap = l.r2_robot_bootstrap * p.bootstrap_gain
                * (robot_fleet * 0.3).min(10.0);
            let comp_ceiling = eff_growth_ceiling + bootstrap;
            // Self-replication capacity injection: an autonomous fleet builds
            // its OWN new factories, mines, and tooling, so the manufacturing
            // capacity compounds at a rate that is no longer set by human capex
            // (`component_base_growth`, ~1.7x/yr) but climbs toward the machine
            // ceiling as autonomy rises. This — not merely lifting the ceiling —
            // is what makes the capacity-bound early/mid period accelerate; the
            // legacy human-capex growth was well below even the WWII ceiling, so
            // a higher ceiling with no faster driver changed nothing.
            // Capacity yield: the reinforcing/balancing loops that act on HOW
            // MUCH capacity each unit of autonomous reinvestment stands up (the
            // active bind), rather than on unit cost (which floors out and feeds
            // only the inert labor-arbitrage channel).
            //  R-cost/efficiency: robot-built robots are more capable per unit of
            //    effort as autonomy compounds, so each reinvested robot builds
            //    MORE capacity (learn_boost > 1).
            //  R-materials (self-supply): robots mine and refine their own inputs,
            //    relieving the feedstock constraint on capacity (mat_supply > 1).
            //  B-materials (depletion): an exponential robot economy pressures ore
            //    grades and refining, throttling capacity with sqrt(fleet); at
            //    extreme scale this overtakes self-supply (mat_deplete > 1),
            //    putting a physical floor under the loop.
            let learn_boost =
                1.0 + p.robot_self_replication * p.learning_autonomy_gain * mfg_autonomy;
            let mat_supply =
                1.0 + p.robot_self_replication * p.materials_selfsupply_gain * mfg_autonomy;
            let mat_deplete = 1.0 + p.robot_self_replication * p.materials_depletion_gain
                * (robot_fleet / p.materials_depletion_half_m).sqrt();
            let capacity_yield = learn_boost * mat_supply / mat_deplete;
            let self_repl_growth = p.robot_self_replication
                * eff_reinvest * mfg_autonomy * p.machine_ceiling * capacity_yield;
            let comp_growth = (p.component_base_growth
                + l.b1_supply_response * p.component_supply_gain * comp_excess
                + bootstrap * 0.2
                + self_repl_growth)
                .min(comp_ceiling * ceiling_mult);
            // NB (audit DO-FIRST #2): component_capacity can drift far above
            // realized production once a downstream ceiling (materials/power)
            // binds — but that drift is a SLACK variable: capacity only affects
            // output when it is itself the binding min(), where cap/prod≈1. The
            // substantive part of #2's concern — the fleet being insensitive to
            // materials — was resolved by DO-FIRST #3 (the bounded Liebig ceiling
            // now gates the fleet). A utilization gate was trialed here but
            // perturbed the well-tested self-replication contracts for a purely
            // cosmetic cap/prod ratio, so it was reverted.
            component_capacity +=
                comp_pipe.step_accel(component_capacity * comp_growth, speedup);

            let avg_phys_wage_k =
                p.physical_wage_bill / p.physical_workers_m * 1e3;
            // ---- critical-inputs supply chain (Liebig minimum) ----
            // Robot output is gated by the single tightest input (reducers,
            // magnets, sensors, chips, copper), each relieved by ASI substitution
            // and threatened by a China embargo. Demand proxy is last year's
            // unclamped robot DEMAND (not clamped production) so the scarcity
            // rent can actually fire when demand outran the ceiling; embargo
            // fires on a genuine rare-earth shock, not any minerals shock.
            let mat = materials_state.step(
                &p.materials,
                asi,
                asi_years,
                prev_robot_demand,
                gfx.rare_earth_embargo,
            );
            mat_binding = mat.binding;
            mat_ceiling_m = mat.robot_ceiling_m;
            // Minerals shocks pass through to delivered robot cost
            // (magnets 5-10% of humanoid BOM; copper elasticity 0.08), plus the
            // scarcity rent on the binding critical input.
            let robot_cost_eff = robot_cost * gfx.comp_cost_mult
                * metals_index.powf(0.08) * mat.cost_mult;
            robot_cost_paid = robot_cost_eff;
            let payback_years =
                robot_cost_eff / (avg_phys_wage_k * p.robot_hew).max(1e-9);
            let econ_pull = (2.0 / payback_years.max(0.25)).clamp(0.0, 3.0);
            let t_rob = (year - p.robotics_year) as f64;
            // ASI dissolves integration friction: the adoption midpoint moves
            // from ~4 years toward ~2 as robots self-integrate.
            let midpoint = 4.0 * (1.0 - p.asi_integration_relief * asi);
            let deploy_ramp = logistic(0.9 * (t_rob - midpoint));
            let (phys_pool, addressable) = match &demo_out {
                Some(d) => (d.phys_pool_m, d.physical_addressable_eff),
                None => (p.physical_workers_m, p.physical_addressable),
            };
            let care_pull = demo_out.as_ref().map_or(0.0, |d| d.robot_pull_units_m);
            let fleet_target = phys_pool * addressable
                * deploy_ramp * (econ_pull / 2.0).min(1.0)
                + care_pull;
            // Labor-substitution demand: bring the fleet up to the human-work
            // target (this is the WWII-analogue, human-labor-capped channel).
            let replacement = (fleet_target
                - robot_fleet * (1.0 - p.robot_attrition))
                .max(0.0);
            // Self-replication demand: an autonomous fleet is NOT demand-capped
            // by human-labor substitution. A `reinvest_share` slice of what the
            // fleet can produce is plowed back into building MORE of the robot
            // economy — the factories, mines, refineries, and grid that make
            // robots — which is itself robot demand scaling with the FLEET, not
            // the human workforce. This is the self-sustaining exponential; it
            // is bounded by machine-ceiling capacity above and grid power below,
            // not by how many human jobs are left to take.
            let self_repl_demand =
                p.robot_self_replication * eff_reinvest * mfg_autonomy * robot_fleet;
            let robot_demand =
                (replacement + self_repl_demand).max(p.robot_prod_2028_m * 0.5);
            prev_robot_demand = robot_demand; // lagged input to next year's scarcity rent
            // A minerals embargo is a hard supply gate: ex-China magnet
            // capacity caps western output regardless of price. The Liebig
            // ceiling is the harder, structural version: the single tightest
            // critical input (reducers early, then magnets) caps output until
            // ASI substitution designs the chokepoint out.
            robot_prod = robot_demand
                .min(component_capacity * gfx.comp_supply_mult)
                .min(mat.robot_ceiling_m);
            // ---- POWER GATE: robots and compute share ONE grid ----
            // A fielded fleet must be RUN, not just built: you cannot power 8B
            // robots (~16 TW at 2 kW each) unless the grid exists. After compute
            // takes its share of the grid, whatever remains caps how large a
            // fleet can actually operate. This is where the robot power draw
            // BITES on the fleet itself (not merely on compute headroom), and
            // where robots building their OWN generation pays off — the grid the
            // fleet is capped against includes the power robots stood up last
            // year (folded into ai_power above). Closes R-energy ⇄ B-grid.
            if p.robot_kw_each > 0.0 {
                let compute_draw_gw = compute_stock * gw_per_unit * power_jevons_mult;
                let robot_grid_gw =
                    (ai_power + space.orbital_gw_equiv - compute_draw_gw).max(0.0);
                // fleet in millions = grid_GW / kW_per_robot (units as above).
                let max_powered_fleet = robot_grid_gw / p.robot_kw_each;
                let powered_room =
                    (max_powered_fleet - robot_fleet * (1.0 - p.robot_attrition)).max(0.0);
                robot_prod = robot_prod.min(powered_room);
            }
            let comp_utilization = robot_demand / component_capacity.max(1e-9);
            component_margin += p.price_adjustment
                * (margin_from(comp_utilization.min(1.35), 0.8) - component_margin);

            cum_robots += robot_prod;
            // R-cost (reinforcing): robot-built robots are cheaper because the
            // robot labor inside the factory is ~free, so autonomy buys extra
            // effective doublings on the Wright curve. Cheaper robots → shorter
            // payback (econ_pull above) → more demand → more volume → cheaper
            // still, bounded below by the hard cost floor.
            let doublings = (cum_robots / 0.06).max(1.0).log2()
                * (1.0 + p.robot_self_replication * p.learning_autonomy_gain * mfg_autonomy);
            robot_cost = (p.robot_cost_2028_k
                * (1.0 - p.robot_learning_rate).powf(doublings))
                .max(p.robot_cost_floor_k);
            robot_fleet = robot_fleet * (1.0 - p.robot_attrition) + robot_prod;
            // Carry this year's autonomy forward: it drives next year's compute-
            // infra flywheel (ceilings/speedup) and robot-built grid power.
            autonomy_prev = mfg_autonomy;
        }

        let phys_hew = robot_fleet * p.robot_hew;
        let demo_phys_pool =
            demo_out.as_ref().map_or(p.physical_workers_m, |d| d.phys_pool_m);
        let pd_target = (phys_hew / demo_phys_pool).min(
            demo_out
                .as_ref()
                .map_or(p.physical_addressable, |d| d.physical_addressable_eff),
        );
        let prev_pd = 1.0 - phys_workers_m / p.physical_workers_m;
        let pd = pd_target
            .min(prev_pd + p.max_physical_displacement_rate)
            .max(prev_pd);
        phys_workers_m = p.physical_workers_m * (1.0 - pd);

        // ---- pools & profits ----
        let avg_cog_wage = p.cognitive_wage_bill / p.cognitive_workers_m;
        let avg_phys_wage = p.physical_wage_bill / p.physical_workers_m;
        // Wage compression (new-dynamic, gated): a growing displaced/underemployed
        // reserve compresses the PRICE of the remaining jobs. The effective average
        // wage tracks a target `1 - gain*displacement` with sticky-wage lag, floored
        // (minimum wage + transfers + essential-worker premium keep it off zero).
        // Applied ONLY to the human WAGE POOLS below (not to the displaced-work value
        // benchmark or robot_services), so the effect is the labor-income price
        // channel the wage-linked shorts key on. gain = 0 (default) pins the index at
        // 1.0 → baseline byte-identical.
        const WAGE_FLOOR: f64 = 0.45;
        let cog_wage_target = (1.0 - p.wage_compression_cog_gain * disp).max(WAGE_FLOOR);
        let phys_wage_target = (1.0 - p.wage_compression_phys_gain * pd).max(WAGE_FLOOR);
        wage_index_cog += 0.5 * (cog_wage_target - wage_index_cog);
        wage_index_phys += 0.5 * (phys_wage_target - wage_index_phys);
        let displaced_value = disp * p.cognitive_workers_m * avg_cog_wage;
        let ai_services = displaced_value * 0.45
            + (cognitive_task_index - 1.0) * p.cognitive_wage_bill * 0.06;

        let years_in = year - p.start_year;
        let casualty = |pool0: f64, beta: f64, drift: f64| -> f64 {
            let organic = pool0 * (1.0 + drift).powi(years_in);
            organic * (1.0 - beta * disp).max(0.05)
        };

        let pools = Pools {
            ai_services,
            silicon: ai_capex * p.silicon_share_of_capex,
            ip_tolls: ai_capex * 0.10,
            dc_infra: ai_capex * (1.0 - p.silicon_share_of_capex),
            power_equipment: p.power_equip_cost_per_gw * power_additions,
            electricity: used_power * 8760.0 * electricity_price / 1e6,
            robots: robot_prod * robot_cost_paid / 1e3,
            robot_components: robot_prod * robot_cost_paid / 1e3 * 0.55,
            robot_services: pd * p.physical_workers_m * avg_phys_wage * 0.35,
            it_services: casualty(p.it_services_pool, p.it_services_beta, 0.04),
            bpo: casualty(p.bpo_pool, p.bpo_beta, 0.03),
            seat_saas: casualty(p.seat_saas_pool, p.saas_beta, 0.08),
            prof_info: casualty(p.prof_info_pool, p.prof_info_beta, 0.05),
            human_cognitive_wages: human_cog_m * avg_cog_wage * wage_index_cog,
            human_physical_wages: phys_workers_m * avg_phys_wage * wage_index_phys,
            gdp_index: gdp,
        };
        let electricity_margin = (0.30
            + 0.5 * (electricity_price / p.electricity_price_normal - 1.0))
            .min(0.6);
        let profits = Profits {
            ai_services: pools.ai_services * p.ai_services_margin,
            silicon: pools.silicon * silicon_margin,
            ip_tolls: pools.ip_tolls * ip_toll_margin,
            dc_infra: pools.dc_infra * p.normal_margin,
            power_equipment: pools.power_equipment * power_margin,
            electricity: pools.electricity * electricity_margin,
            robots: pools.robots * p.normal_margin,
            robot_components: pools.robot_components * component_margin,
            robot_services: pools.robot_services * p.normal_margin,
            it_services: pools.it_services * p.normal_margin,
            bpo: pools.bpo * p.normal_margin,
            seat_saas: pools.seat_saas * p.normal_margin,
            prof_info: pools.prof_info * p.normal_margin,
        };

        // ---- macro ----
        let new_disp = (disp - prev_disp_macro).max(0.0);
        prev_disp_macro = disp;
        let ai_share = (ai_services + pools.robot_services) / gdp;
        // Transfers offset part of transition drag (demand backstop);
        // compliance costs subtract (distinct channels, design doc §5.4).
        let drag_mult = if soc_on { soc.drag_multiplier(&p.society) } else { 1.0 };
        // Compliance is a cost on the AI SECTOR's output, not the whole
        // economy (red-team round 3: charging world GDP overstated the
        // loss by the inverse of the sector share).
        let compliance = if soc_on {
            soc.compliance_cost(&p.society) * ai_share.min(0.2) * 5.0
        } else {
            0.0
        };
        let unrest_cost = if soc_on { soc.unrest_gdp_cost() } else { 0.0 };
        // Equity wealth-effect (gated, chains off the spine): the YoY change in
        // equity_sentiment moves consumption via MPC x the AI complex's wealth share.
        // Zero when either gain is off (a frozen sentiment has no change).
        let prev_es = out.last().map_or(1.0, |s| s.equity_sentiment);
        let wealth_effect = p.wealth_effect_gain * (equity_sentiment - prev_es) * ai_share;
        gdp *= 1.0
            + (p.base_gdp_growth + p.productivity_passthrough * ai_share * 0.5
                - p.transition_drag * new_disp * (p.cognitive_wage_bill / gdp)
                    * drag_mult
                - compliance
                - unrest_cost
                - bfx.gdp_drag
                + wealth_effect);

        // ---- demography advances first: it filters what politics sees ----
        let election = (year - p.start_year) % p.society.election_period == 0;
        let gdp_growth_this_year = if let Some(prev) = out.last() {
            gdp / prev.gdp - 1.0
        } else {
            p.base_gdp_growth
        };
        let this_demo = if demo_on {
            let d = demo.step(
                &p.demography,
                disp,
                robot_prod * p.robot_hew,
                soc.sentiment,
                soc.transfer_share(),
                gdp_growth_this_year,
                election,
                pd,
                bio_out.as_ref().map_or(0.0, |b| b.enhancement_solidarity_erosion),
                bio_out.as_ref().map_or(1.0, |b| b.age_creep_mult),
            );
            Some(d)
        } else {
            None
        };

        // ---- society stocks advance on this year's outcomes ----
        if soc_on {
            let lag = p.society.erosion_lag as usize;
            let lagged_rate = if out.len() >= lag + 1 {
                (out[out.len() - lag].cog_displacement
                    - out[out.len() - lag - 1].cog_displacement)
                    .max(0.0)
            } else {
                0.0
            };
            let incident = p.incident_year == year || bfx.incident;
            if (incident && p.incident_dread) || bfx.arm_dread {
                dread_armed = true;
            }
            // Demography rewires the political inputs: society sees the
            // VISIBLE displacement rate (net of hiring freezes, vacancy
            // filling, restriction masking) against an endogenous
            // attrition threshold, and transfer size/cap gate on
            // solidarity + fiscal aging.
            let (soc_rate, sp_eff, suppress_transfers) = match &this_demo {
                Some(d) => {
                    let mut sp = p.society.clone();
                    sp.attrition_threshold = d.attrition_threshold;
                    sp.transfer_cap = d.transfer_cap_eff;
                    sp.transfer_step *= d.transfer_step_mult;
                    sp.transfer_crisis_step *= d.transfer_step_mult;
                    if d.restriction_fired {
                        // restriction-first: the cheap valve fires INSTEAD
                        // of the transfer step this cycle
                        sp.b5_relief = 0.0;
                    }
                    (
                        d.visible_cog_rate + d.visible_phys_rate,
                        sp,
                        d.restriction_fired,
                    )
                }
                None => (new_disp, p.society.clone(), false),
            };
            soc.step(
                &sp_eff,
                soc_rate,
                adopt,
                adopt_delta,
                lagged_rate,
                election,
                incident,
                incident && p.incident_dread,
            );
            if let Some(d) = &this_demo {
                // Channel B (youth blockage) is a SEPARATE sentiment
                // inflow — the historically revolutionary variable; it
                // never touches labor_power (blocked youth can't strike).
                soc.sentiment = (soc.sentiment
                    + d.youth_sentiment_inflow * (1.0 - soc.sentiment))
                    .min(1.0);
                if suppress_transfers {
                    // restriction vents SALIENCE, not grievance
                    soc.sentiment = (soc.sentiment
                        - p.demography.restriction_sent_relief)
                        .max(0.0);
                }
                // tension multiplies the unrest hazard (IMF/Barrett
                // self-excitation), applied to the boil level
                soc.unrest =
                    (soc.unrest * (1.0 + 0.5 * (d.unrest_mult - 1.0))).min(1.0);
            }
        }
        demo_out = this_demo;

        // ---- macro-finance: bond market prices the transfer ramp (B11) ----
        if macro_on {
            // Endogenous inputs (audit DO-FIRST #4): the debt-financing share
            // follows society's dynamic winner-tax maturation (0.6→0.15), and
            // nominal growth is THIS year's realized real GDP growth + a ~2%
            // inflation add-on — not a pinned 5% that manufactured (g−r)<0 and
            // a permanent snowball regardless of the actual boom.
            let debt_share = if soc_on { soc.debt_financing_share(&p.society) } else { 0.6 };
            let ai_ig = (ai_capex * (1.0 - p.internal_funding_share) / gdp).max(0.0);
            macro_out = Some(macrost.step(
                &p.macrofin,
                soc.transfer_share(),
                debt_share,
                ai_ig,
                (gdp_growth_this_year + 0.02).max(0.0),
            ));
            // debt-service squeeze on the transfer cap (fiscal collision)
            if let Some(m) = &macro_out {
                let squeeze = m.transfer_cap_squeeze;
                if squeeze > 0.0 {
                    soc.throttle_transfer_cap(squeeze);
                }
            }
        }

        // ---- energy / food / regions satellite layers ----
        // Energy: the generation mix that supplies the grid the economy runs on.
        let grid_demand_gw = compute_stock * gw_per_unit * power_jevons_mult + robot_power_gw;
        let energy_out = energy_state.step(&p.energy, grid_demand_gw, 1.0, asi);
        // Food: the fertilizer(Haber-Bosch) driver is the ENERGY-cost environment,
        // not datacenter compute pricing. Audit C4: this was fed
        // `electricity_price/normal`, a datacenter-scarcity ratio that is one-sided
        // (AI crunch pushes it up, never down), so fertilizer was floored at 1.0 and
        // the clean-N relief path was unreachable — a one-way "AI crunch → food up"
        // wire. Feed the energy layer's blended `cost_index` instead: it falls below
        // 1.0 as solar+battery Wright's law compounds, and once green ammonia
        // (electrolysis, food.green_ammonia_year) severs the gas wire that cheap-
        // electricity signal is exactly the ammonia driver. This gives the energy
        // layer a genuine downstream consumer.
        let fuel_price_index = energy_out.cost_index;
        // Carry this year's generation cost into next year's core price blend (C3).
        energy_cost_index_prev = energy_out.cost_index;
        let food_out = food_state.step(&p.food, fuel_price_index, adopt.min(1.0), year);
        // Regions: decompose the transition into US/China/EU bloc trajectories.
        // C10: feed the Taiwan chip-supply shock (chip_mult net of the one-time
        // invasion destruction) so a blockade/invasion reshapes the China-vs-US
        // split. Identity (1.0) on the deterministic baseline (empty geo_shocks).
        let chip_supply_index = (gfx.chip_mult * (1.0 - gfx.chip_destruction)).clamp(0.0, 1.0);
        let region_out = region_state.step(
            &p.regions,
            (adopt - prev_adopt_region).max(0.0),
            (power_additions / ai_power.max(1e-9)).clamp(0.0, 0.5),
            disp.max(pd),
            asi,
            chip_supply_index,
        );
        prev_adopt_region = adopt;
        // Food → tension: last year's food unrest feeds this year's political
        // stress (gated; 0 by default keeps the layers pure satellites).
        if p.food_tension_gain > 0.0 && soc_on {
            soc.add_external_stress(p.food_tension_gain * food_unrest_prev);
        }
        food_unrest_prev = food_out.unrest_pressure;

        last_capex = ai_capex.max(1e-6);

        out.push(YearState {
            year,
            binding,
            ai_capex,
            compute_stock,
            algo_eff,
            ai_power_gw: used_power,
            power_utilization,
            chip_utilization,
            silicon_margin,
            power_margin,
            component_margin,
            electricity_price,
            ai_hew_m: ai_hew,
            cog_displacement: disp,
            cognitive_task_index,
            adoption_friction: friction,
            adoption_level: adopt,
            robot_prod_m: robot_prod,
            robot_fleet_m: robot_fleet,
            robot_cost_k: robot_cost,
            component_capacity_m: component_capacity,
            materials_ceiling_m: mat_ceiling_m,
            materials_binding: mat_binding.to_string(),
            firm_power_gw: energy_out.firm_power_gw,
            solar_gw: energy_out.solar_gw,
            battery_gwh: energy_out.battery_gwh,
            clean_power_share: energy_out.clean_share,
            electricity_cost_index: energy_out.cost_index,
            food_price_index: food_out.food_price_index,
            food_unrest: food_out.unrest_pressure,
            bloc_capability: region_out.capability.clone(),
            bloc_stress: region_out.stress.clone(),
            bloc_fracture_risk: region_out.fracture_risk.clone(),
            china_us_capability_gap: region_out.china_us_gap,
            west_capability_share: region_out.west_share,
            phys_displacement: pd,
            sector_debt,
            credit_multiplier: credit_mult,
            perceived_growth,
            queue_ratio,
            capacity_glut,
            equity_sentiment,
            ip_toll_margin,
            gdp,
            sentiment: soc.sentiment,
            reg_enforcement: soc.reg_enforcement,
            transfer_share: soc.transfer_share(),
            labor_power: soc.labor_power,
            inst_trust: soc.inst_trust,
            consumer_trust: soc.consumer_trust,
            blocked_entrants_m: demo.blocked_entrants_m,
            visible_disp_rate: demo_out
                .as_ref()
                .map_or(new_disp, |d| d.visible_cog_rate + d.visible_phys_rate),
            tension: demo.tension,
            solidarity: demo.solidarity,
            migration_openness: demo.migration_openness,
            cog_pool_m: demo.cog_pool_m,
            phys_pool_m: demo.phys_pool_m,
            autonomization_index: (ai_capex / gdp)
                / ((pools.human_cognitive_wages + pools.human_physical_wages)
                    / gdp)
                    .max(1e-9),
            meltdown_ratio: new_disp.max(0.0)
                / (soc.transfer_share() + soc.reg_enforcement + 0.02),
            bio_hazard: bio_out.as_ref().map_or(0.0, |b| b.bio_operational_uplift),
            cyber_hazard: bfx.spread,
            drug_pool_b: bio_out.as_ref().map_or(0.0, |b| b.ai_drug_pool_b),
            longevity_pool_b: bio_out.as_ref().map_or(0.0, |b| b.longevity_pool_b),
            bci_pool_b: bio_out.as_ref().map_or(0.0, |b| b.bci_pool_b),
            bio_materials_pool_b: bio_out.as_ref().map_or(0.0, |b| b.bio_materials_pool_b),
            long_rate: macro_out.as_ref().map_or(0.048, |m| m.long_rate),
            gov_debt_gdp: macro_out.as_ref().map_or(1.0, |m| m.gov_debt_gdp),
            debt_service: macro_out.as_ref().map_or(0.048, |m| m.debt_service),
            orbital_gw_equiv: space.orbital_gw_equiv,
            launch_cost_per_kg: space.launch_cost_per_kg,
            launch_capacity_tpy: space.launch_capacity_tpy,
            pools,
            profits,
        });
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pipeline_conserves() {
        let mut pipe = Pipeline::new(2, 0.0);
        let mut total_in = 0.0;
        let mut total_out = 0.0;
        for i in 0..10 {
            let inflow = i as f64;
            total_in += inflow;
            total_out += pipe.step(inflow);
        }
        assert!((total_in - total_out - pipe.in_transit()).abs() < 1e-9);
    }

    #[test]
    fn baseline_runs_and_power_binds() {
        let states = simulate(&Params::default());
        assert_eq!(states.len(), 11);
        let power_years = states.iter()
            .filter(|s| s.binding == Binding::Power).count();
        assert!(power_years >= 6, "power bound {} years", power_years);
    }
}
